// Schritte Plus Neu A1.1 — Vocabulary
// Source: Schritte Plus Neu A1.1 textbook (Hueber)
// Organized by Lektion (lesson) per the book's structure
// English translations reused from VOCAB_DATA where overlapping, otherwise from PDF

// Word shape: [german, english, catIdx, typeIdx]
// catIdx: 0 = Anweisungen im Kurs, 1-7 = Lektion 1-7
// typeIdx: 0 = Noun, 1 = Verb, 2 = Adjective, 3 = Grammar, 4 = Expression, 5 = Foundational

export const VOCAB_A11_DATA = {
  cats: [
    "Anweisungen im Kurs",
    "Lektion 1: Guten Tag",
    "Lektion 2: Meine Familie",
    "Lektion 3: Einkaufen",
    "Lektion 4: Meine Wohnung",
    "Lektion 5: Mein Tag",
    "Lektion 6: Freizeit",
    "Lektion 7: Kinder und Schule"
  ],
  types: ["Noun","Verb","Adjective","Grammar","Expression","Foundational"],
  words: [
    // ===== Cat 0: Anweisungen im Kurs (Classroom Instructions) =====
    ["ansehen","to look at",0,1],
    ["das Bild","picture, image",0,0],
    ["hören","to listen",0,1],
    ["noch einmal","once more, again",0,4],
    ["ankreuzen","to mark / check",0,1],
    ["zuordnen","to match, assign",0,1],
    ["ergänzen","to complete, fill in",0,1],
    ["machen","to make, do",0,1],
    ["der Kurs","course, class",0,0],
    ["sprechen","to speak",0,1],
    ["lesen","to read",0,1],
    ["das Gespräch","conversation, dialogue",0,0],
    ["spielen","to play, act out",0,1],
    ["suchen","to search, look for",0,1],
    ["zeigen","to show, point",0,1],
    ["fragen","to ask",0,1],
    ["markieren","to highlight, mark",0,1],
    ["die Frage","question",0,0],
    ["nachsprechen","to repeat (after sb.)",0,1],
    ["raten","to guess",0,1],
    ["das Wort","word",0,0],
    ["die Lektion","lesson",0,0],
    ["meinen","to mean, think",0,1],
    ["sagen","to say",0,1],
    ["notieren","to note down",0,1],
    ["vergleichen","to compare",0,1],
    ["schreiben","to write",0,1],
    ["variieren","to vary",0,1],
    ["erzählen","to tell, narrate",0,1],
    ["arbeiten","to work",0,1],
    ["zeichnen","to draw",0,1],
    ["verbinden","to connect",0,1],
    ["die Antwort","answer",0,0],

    // ===== Cat 1: Lektion 1 — Guten Tag =====
    // Foto-Hörgeschichte
    ["ich","I",1,3],
    ["heißen","to be called",1,1],
    ["der Name","name",1,0],
    ["kommen","to come",1,1],
    ["Deutschland","Germany",1,0],
    ["Deutsch","German (language)",1,0],
    ["und","and",1,5],
    ["ein bisschen","a little bit",1,4],
    // A — Begrüßung und Abschied
    ["Guten Tag","Good day / Hello",1,4],
    ["Hallo","Hello",1,4],
    ["Auf Wiedersehen","Goodbye",1,4],
    ["Tschüs","Bye (informal)",1,4],
    ["der Herr","Mr., gentleman",1,0],
    ["das Kind","child",1,0],
    ["Guten Abend","Good evening",1,4],
    ["die Dame","lady",1,0],
    ["willkommen","welcome",1,4],
    ["bei","at, with",1,5],
    ["die Musik","music",1,0],
    ["international","international",1,2],
    ["Guten Morgen","Good morning",1,4],
    ["die Frau","Mrs., woman",1,0],
    ["danke","thank you",1,4],
    ["Gute Nacht","Good night",1,4],
    ["der Papa","dad",1,0],
    // B — Sich vorstellen
    ["sein","to be",1,1],
    ["Entschuldigung","excuse me, sorry",1,4],
    ["wie","how",1,3],
    ["Sie (formal)","you (formal)",1,3],
    ["wer","who",1,3],
    ["ja","yes",1,5],
    ["nein","no",1,5],
    // C — Herkunft und Sprachen
    ["woher","where from",1,3],
    ["aus","from",1,5],
    ["du","you (informal)",1,3],
    ["Österreich","Austria",1,0],
    ["die Schweiz","Switzerland",1,0],
    ["aha","I see!",1,4],
    ["toll","great, awesome",1,2],
    ["interessant","interesting",1,2],
    ["was","what",1,3],
    ["auch","also, too",1,5],
    ["die Sprache","language",1,0],
    // D — Buchstaben und Alphabet
    ["der Buchstabe","letter (of alphabet)",1,0],
    ["das Alphabet","alphabet",1,0],
    ["Wie bitte?","Pardon? Sorry?",1,4],
    ["buchstabieren","to spell",1,1],
    ["bitte","please",1,4],
    ["die Firma","company, firm",1,0],
    ["Vielen Dank","Thank you very much",1,4],
    ["Auf Wiederhören","Goodbye (on phone)",1,4],
    // E — Personalien
    ["die Adresse","address",1,0],
    ["die Visitenkarte","business card",1,0],
    ["der Vorname","first name",1,0],
    ["der Familienname","last name, surname",1,0],
    ["die Straße","street",1,0],
    ["die Stadt","city",1,0],
    ["das Land","country",1,0],
    ["die E-Mail","email",1,0],
    ["das Telefon","telephone",1,0],
    ["das Formular","form",1,0],
    ["die Fremdsprache","foreign language",1,0],
    ["die Anmeldung","registration",1,0],
    ["die Postleitzahl","zip code",1,0],
    // Länder und Sprachen
    ["Polen","Poland",1,0],
    ["die Türkei","Turkey",1,0],
    ["Spanien","Spain",1,0],
    ["Ungarn","Hungary",1,0],
    ["Rumänien","Romania",1,0],
    ["Syrien","Syria",1,0],
    ["Bulgarien","Bulgaria",1,0],
    ["Italien","Italy",1,0],
    ["Griechenland","Greece",1,0],
    // --- Redemittel (Useful Expressions) ---
    // Begrüßung
    ["(Herzlich) Willkommen.","(Warm) Welcome.",1,4],
    ["Freut mich.","Nice to meet you.",1,4],
    // Name
    ["Wie heißen Sie?","What is your name? (formal)",1,4],
    ["Wie heißt du?","What is your name? (informal)",1,4],
    ["Wer bist du?","Who are you? (informal)",1,4],
    ["Wer sind Sie?","Who are you? (formal)",1,4],
    ["Wie ist Ihr Name?","What is your name? (formal)",1,4],
    ["Wer ist das?","Who is that?",1,4],
    ["Ich heiße ...","My name is ...",1,4],
    ["Mein Name ist ...","My name is ...",1,4],
    ["Das ist Herr ...","This is Mr. ...",1,4],
    // Herkunft
    ["Woher kommen Sie?","Where are you from? (formal)",1,4],
    ["Woher kommst du?","Where are you from? (informal)",1,4],
    ["Ich komme aus ...","I come from ...",1,4],
    // Sprache
    ["Was sprechen Sie?","What languages do you speak? (formal)",1,4],
    ["Was sprichst du?","What languages do you speak? (informal)",1,4],
    ["Ich spreche Deutsch.","I speak German.",1,4],
    ["Sie sprechen gut Deutsch.","You speak German well. (formal)",1,4],
    ["Du sprichst gut Deutsch.","You speak German well. (informal)",1,4],
    ["Nur ein bisschen.","Just a little.",1,4],
    // Entschuldigung
    ["Tut mir leid.","I'm sorry.",1,4],
    // Bitten und Danken
    ["Ist Frau ... da, bitte?","Is Mrs. ... there, please?",1,4],
    ["Buchstabieren Sie, bitte.","Please spell that.",1,4],
    // Strategien
    ["Ja, stimmt.","Yes, that's right.",1,4],
    ["Ja, gut.","Yes, good.",1,4],
    ["Einen Moment, bitte.","One moment, please.",1,4],
    ["Ich weiß es nicht.","I don't know.",1,4],

    // ===== Cat 2: Lektion 2 — Meine Familie =====
    // Foto-Hörgeschichte
    ["lernen","to learn",2,1],
    ["der Park","park",2,0],
    ["die Pause","break, pause",2,0],
    ["die Familie","family",2,0],
    ["der Vater","father",2,0],
    ["die Großeltern","grandparents",2,0],
    ["die Mutter","mother",2,0],
    ["die Eltern","parents",2,0],
    ["der Bruder","brother",2,0],
    ["die Geschwister","siblings",2,0],
    ["das Jahr","year",2,0],
    ["leben","to live",2,1],
    ["in","in",2,5],
    // A — Befinden
    ["gut","good, well",2,2],
    ["super","great, super",2,4],
    ["na ja","well... (hesitation)",2,4],
    ["ach","oh (expression)",2,4],
    ["so","so",2,5],
    ["sehr","very",2,5],
    // B — Familie
    ["der Enkel","grandson",2,0],
    ["die Enkelin","granddaughter",2,0],
    ["die Tochter","daughter",2,0],
    ["der Sohn","son",2,0],
    ["die Schwester","sister",2,0],
    ["die Oma","grandma",2,0],
    ["der Mann","man, husband",2,0],
    ["der Opa","grandpa",2,0],
    ["dein","your (informal)",2,3],
    ["mein","my",2,3],
    ["Ihr (formal)","your (formal)",2,3],
    ["der Ehemann","husband",2,0],
    ["die Ehefrau","wife",2,0],
    ["falsch","wrong, false",2,2],
    // C — Personalien
    ["sie","she",2,3],
    ["zusammen","together",2,5],
    ["geschieden","divorced",2,2],
    ["er","he",2,3],
    ["wohnen","to live, reside",2,1],
    ["jetzt","now",2,5],
    ["ihr","you (plural informal)",2,3],
    ["wir","we",2,3],
    // D — Zahlen und Personalien
    ["die Zahl","number",2,0],
    ["wo","where",2,3],
    ["geboren","born",2,2],
    ["die Nummer","number (phone)",2,0],
    ["verheiratet","married",2,2],
    ["haben","to have",2,1],
    ["der Geburtsort","place of birth",2,0],
    ["der Wohnort","place of residence",2,0],
    ["der Familienstand","marital status",2,0],
    ["ledig","single",2,2],
    ["verwitwet","widowed",2,2],
    ["das Alter","age",2,0],
    // E — Geografie
    ["der Norden","north",2,0],
    ["der Osten","east",2,0],
    ["der Süden","south",2,0],
    ["der Westen","west",2,0],
    ["die Hauptstadt","capital city",2,0],
    // --- Redemittel (Useful Expressions) ---
    // Befinden
    ["Wie geht's?","How are you?",2,4],
    ["Wie geht es Ihnen?","How are you? (formal)",2,4],
    ["Wie geht es dir?","How are you? (informal)",2,4],
    ["Und Ihnen?","And you? (formal)",2,4],
    ["Und dir?","And you? (informal)",2,4],
    ["Sehr gut, danke.","Very good, thanks.",2,4],
    ["Gut, danke.","Good, thanks.",2,4],
    ["Na ja, es geht.","Well, so-so.",2,4],
    ["Ach, nicht so gut.","Oh, not so good.",2,4],
    ["Auch gut, danke.","Also fine, thanks.",2,4],
    // Andere vorstellen
    ["Das ist mein Vater.","This is my father.",2,4],
    ["Das sind meine Großeltern.","These are my grandparents.",2,4],
    ["Er kommt aus ...","He comes from ...",2,4],
    ["Sie kommt aus ...","She comes from ...",2,4],
    ["Er lebt in ...","He lives in ...",2,4],
    ["Sie lebt in ...","She lives in ...",2,4],
    // Angaben zur Person
    ["Wo sind Sie geboren?","Where were you born?",2,4],
    ["Ich bin in ... geboren.","I was born in ...",2,4],
    ["Wo wohnen Sie?","Where do you live?",2,4],
    ["Ich wohne in ...","I live in ...",2,4],
    ["Wie ist Ihre Adresse?","What is your address?",2,4],
    ["Wie ist Ihre Telefonnummer?","What is your phone number?",2,4],
    ["Sind Sie verheiratet?","Are you married?",2,4],
    ["Ja, ich bin verheiratet.","Yes, I am married.",2,4],
    ["Nein, ich bin ledig.","No, I am single.",2,4],
    ["Haben Sie Kinder?","Do you have children?",2,4],
    ["Wie alt ist Ihr Kind?","How old is your child?",2,4],
    ["Wie alt sind Ihre Kinder?","How old are your children?",2,4],
    // Ort
    ["Hamburg liegt in Deutschland.","Hamburg is in Germany.",2,4],
    ["... ist die Hauptstadt von ...","... is the capital of ...",2,4],
    // Strategien
    ["Ja, genau.","Yes, exactly.",2,4],
    ["Nein, falsch.","No, wrong.",2,4],

    // ===== Cat 3: Lektion 3 — Einkaufen =====
    // D — Preise und Mengenangaben
    ["der Preis","price",3,0],
    ["der Cent","cent",3,0],
    ["der Prospekt","brochure, flyer",3,0],
    ["das Sonderangebot","special offer",3,0],
    ["das Lebensmittel","food, groceries",3,0],
    ["wie viel","how much",3,4],
    ["kosten","to cost",3,1],
    ["das Kilo","kilogram",3,0],
    ["das Gramm","gram",3,0],
    ["das Pfund","pound (500g)",3,0],
    ["der Liter","liter",3,0],
    ["die Flasche","bottle",3,0],
    ["die Dose","can, tin",3,0],
    ["die Sahne","cream",3,0],
    ["die Wurst","sausage",3,0],
    ["das Hackfleisch","minced meat",3,0],
    // E — Einkaufen
    ["der Verkäufer","seller, shop assistant",3,0],
    ["die Verkäuferin","saleswoman",3,0],
    ["der Kunde","customer (m.)",3,0],
    ["die Kundin","customer (f.)",3,0],
    ["noch","still, also",3,5],
    ["alles","all, everything",3,3],
    ["möchten","would like",3,1],
    ["finden","to find",3,1],
    ["der Laden","shop, store",3,0],
    ["das Obst","fruit",3,0],
    ["das Gemüse","vegetables",3,0],
    ["die Bäckerei","bakery",3,0],
    ["das Rezept","recipe",3,0],
    ["das Wasser","water",3,0],
    ["der Pfeffer","pepper",3,0],
    // Lebensmittel
    ["die Schokolade","chocolate",3,0],
    ["die Milch","milk",3,0],
    ["der Käse","cheese",3,0],
    ["der Kuchen","cake",3,0],
    ["die Banane","banana",3,0],
    ["das Brot","bread",3,0],
    ["der Apfel","apple",3,0],
    ["die Orange","orange",3,0],
    ["die Butter","butter",3,0],
    ["der Fisch","fish",3,0],
    ["das Ei","egg",3,0],
    ["das Fleisch","meat",3,0],
    ["die Birne","pear",3,0],
    ["der Saft","juice",3,0],
    ["das Brötchen","bread roll",3,0],
    ["der Joghurt","yogurt",3,0],
    ["die Kartoffel","potato",3,0],
    ["die Zwiebel","onion",3,0],
    ["die Tomate","tomato",3,0],
    ["das Mineralwasser","mineral water",3,0],
    // --- Redemittel (Useful Expressions) ---
    // Nachfragen
    ["Was ist das?","What is that?",3,4],
    ["Das ist ein Apfel.","That is an apple.",3,4],
    ["Wie heißt das auf Deutsch?","What is that called in German?",3,4],
    ["Ist das ein Würstchen?","Is that a sausage?",3,4],
    ["Das stimmt.","That's right.",3,4],
    // Beim Einkaufen
    ["Kann ich Ihnen helfen?","Can I help you? (formal)",3,4],
    ["Kann ich dir helfen?","Can I help you? (informal)",3,4],
    ["Bitte schön?","Can I help you? / Here you go.",3,4],
    ["Wo finde ich ...?","Where can I find ...?",3,4],
    ["Ich hätte gern ...","I'd like ...",3,4],
    ["Ich möchte ...","I'd like ...",3,4],
    ["Haben Sie Eier?","Do you have eggs?",3,4],
    ["Wie viel möchten Sie?","How much do you want?",3,4],
    ["Wie viel kostet ein Kilo ...?","How much does a kilo of ... cost?",3,4],
    ["Wie viel kosten 100 Gramm ...?","How much does 100 grams of ... cost?",3,4],
    ["Das macht 2 Euro 50.","That comes to 2 Euro 50.",3,4],
    ["Hier, bitte.","Here you go.",3,4],
    ["Sonst noch etwas?","Anything else?",3,4],
    ["Ja, bitte.","Yes, please.",3,4],
    ["Nein, danke.","No, thanks.",3,4],
    ["Das ist alles.","That's all.",3,4],
    // Mengenangaben
    ["eine Flasche Saft","a bottle of juice",3,4],
    ["ein Liter Milch","a liter of milk",3,4],
    ["ein Pfund Brot","a pound of bread",3,4],
    ["eine Packung Tee","a package of tea",3,4],
    ["ein Becher Sahne","a cup of cream",3,4],
    ["ein Kilo Orangen","a kilo of oranges",3,4],
    ["eine Dose Tomaten","a can of tomatoes",3,4],
    // Strategien
    ["Ja, natürlich.","Yes, of course.",3,4],
    ["Nein, tut mir leid.","No, I'm sorry.",3,4],
    ["die Packung","package",3,0],
    ["der Becher","cup (container)",3,0],
    ["der Tee","tea",3,0],

    // ===== Cat 4: Lektion 4 — Meine Wohnung =====
    // A — Wohnung
    ["die Wohnung","apartment",4,0],
    ["die Lampe","lamp",4,0],
    ["das Zimmer","room",4,0],
    ["die Küche","kitchen",4,0],
    ["das Bad","bathroom",4,0],
    ["alt","old",4,2],
    ["neu","new",4,2],
    ["groß","big, large",4,2],
    ["klein","small",4,2],
    ["hell","bright",4,2],
    ["dunkel","dark",4,2],
    ["teuer","expensive",4,2],
    ["billig","cheap",4,2],
    ["schön","beautiful, nice",4,2],
    ["hässlich","ugly",4,2],
    ["kennen","to know (person)",4,1],
    ["der Flur","hallway",4,0],
    ["die Toilette","toilet",4,0],
    ["der Balkon","balcony",4,0],
    ["das Wohnzimmer","living room",4,0],
    ["das Haus","house",4,0],
    ["hier","here",4,5],
    ["dort","there",4,5],
    // B — Beschreibung
    ["aber","but",4,5],
    ["nicht","not",4,5],
    ["der Monat","month",4,0],
    ["schmal","narrow",4,2],
    ["richtig","right, correct",4,2],
    ["breit","wide",4,2],
    // C — Möbel und Farben
    ["der Schrank","closet, cabinet",4,0],
    ["der Kühlschrank","refrigerator",4,0],
    ["das Sofa","sofa",4,0],
    ["der Tisch","table",4,0],
    ["der Stuhl","chair",4,0],
    ["das Bett","bed",4,0],
    ["der Fernseher","TV set",4,0],
    ["die Dusche","shower",4,0],
    ["der Herd","stove",4,0],
    ["die Badewanne","bathtub",4,0],
    ["der Teppich","carpet, rug",4,0],
    ["der Sessel","armchair",4,0],
    ["die Möbel","furniture",4,0],
    ["das Gerät","device, appliance",4,0],
    ["gefallen","to please, to like",4,1],
    ["die Farbe","color",4,0],
    ["ganz","quite",4,5],
    ["modern","modern",4,2],
    ["schwarz","black",4,2],
    ["grau","gray",4,2],
    ["weiß","white",4,2],
    ["grün","green",4,2],
    ["braun","brown",4,2],
    ["blau","blue",4,2],
    ["rot","red",4,2],
    ["gelb","yellow",4,2],
    // D — Wohnungsanzeigen
    ["der Zentimeter","centimeter",4,0],
    ["mal","times (multiplication)",4,5],
    ["das Handy","mobile phone",4,0],
    ["die Arbeit","work",4,0],
    ["die Anzeige","advertisement",4,0],
    ["nett","nice",4,2],
    ["das Ehepaar","married couple",4,0],
    ["der Garten","garden",4,0],
    ["vermieten","to rent out",4,1],
    ["das Apartment","apartment",4,0],
    ["der Raum","room, space",4,0],
    ["der Stock","floor, story",4,0],
    ["circa","approximately",4,5],
    ["privat","private",4,2],
    ["ab","from",4,5],
    ["sofort","immediately",4,5],
    ["maximal","maximum",4,5],
    ["möbliert","furnished",4,2],
    ["die Garage","garage",4,0],
    ["der Quadratmeter","square meter",4,0],
    ["nur","only",4,5],
    ["die Miete","rent",4,0],
    ["bezahlen","to pay",4,1],
    // E — Kaufen und Verkaufen
    ["verkaufen","to sell",4,1],
    ["etwas","something",4,3],
    ["der Computer","computer",4,0],
    ["der Schreibtisch","desk",4,0],
    ["heute","today",4,5],
    ["welche","Which...?",4,3],
    ["also","so, well",4,5],
    ["ungefähr","approximately",4,5],
    ["der Meter","meter",4,0],
    ["lang","long",4,2],
    ["genau","exactly",4,5],
    ["sehen","to see",4,1],
    ["hoch","high, tall",4,2],
    ["morgen","tomorrow",4,5],
    ["das Regal","shelf",4,0],
    // --- Redemittel (Useful Expressions) ---
    // Gefallen/Missfallen
    ["Wie gefällt dir der Tisch?","How do you like the table? (informal)",4,4],
    ["Wie gefällt Ihnen der Tisch?","How do you like the table? (formal)",4,4],
    ["Wie gefallen dir die Betten?","How do you like the beds? (informal)",4,4],
    ["Wie gefallen Ihnen die Betten?","How do you like the beds? (formal)",4,4],
    ["Sehr gut.","Very good.",4,4],
    ["Ganz gut.","Quite good.",4,4],
    ["Es geht.","It's okay.",4,4],
    ["Nicht so gut.","Not so good.",4,4],
    // Nach dem Ort fragen
    ["Wo ist die Küche?","Where is the kitchen?",4,4],
    ["Ist das hier das Bad?","Is this the bathroom?",4,4],
    ["Ja, das hier ist das Bad.","Yes, this is the bathroom.",4,4],
    ["Ist hier auch ein Arbeitszimmer?","Is there also a study here?",4,4],
    // Beschreiben
    ["Wie ist dein Zimmer?","What is your room like?",4,4],
    ["Es ist teuer.","It's expensive.",4,4],
    ["Es ist nicht teuer.","It's not expensive.",4,4],
    ["Es ist sehr teuer.","It's very expensive.",4,4],
    ["Wie lang ist der Tisch?","How long is the table?",4,4],
    ["Wie breit ist der Tisch?","How wide is the table?",4,4],
    ["Wie hoch ist der Tisch?","How tall is the table?",4,4],
    ["Ungefähr zwei Meter.","Approximately two meters.",4,4],
    ["Genau zwei Meter.","Exactly two meters.",4,4],
    ["Wie groß ist das Bett?","How big is the bed?",4,4],
    ["Welche Farbe hat der Tisch?","What color is the table?",4,4],
    ["Er ist dunkelbraun.","It is dark brown.",4,4],
    // Ein Telefongespräch führen
    ["Sie verkaufen doch ...?","You're selling ..., right?",4,4],
    ["Ist der ... noch da?","Is the ... still available?",4,4],
    ["Wie alt ist er?","How old is it?",4,4],
    ["Was kostet er?","How much does it cost?",4,4],
    ["Und wo wohnen Sie, bitte?","And where do you live, please?",4,4],
    ["In der ... straße.","On ... street.",4,4],
    ["Sind Sie heute zu Hause?","Are you home today?",4,4],
    ["Sind Sie morgen zu Hause?","Are you home tomorrow?",4,4],
    ["Ja, ich bin da.","Yes, I'm home.",4,4],
    ["Nein, ich bin nicht da.","No, I'm not home.",4,4],
    // Strategien
    ["Sagen Sie mal, ...","Tell me, ... (formal)",4,4],
    ["Sag mal, ...","Tell me, ... (informal)",4,4],
    ["Ja, richtig.","Yes, right.",4,4],
    ["Aha, gut!","Oh, good!",4,4],
    ["..., nicht?","..., right?",4,4],
    ["..., oder?","..., or?",4,4],
    ["..., richtig?","..., correct?",4,4],
    ["Schau mal!","Look! (informal)",4,4],
    ["Schauen Sie mal!","Look! (formal)",4,4],
    ["dunkelbraun","dark brown",4,2],
    ["zu Hause","at home",4,4],

    // ===== Cat 5: Lektion 5 — Mein Tag =====
    // Foto-Hörgeschichte & A — Tagesablauf
    ["die Präsentation","presentation",5,0],
    ["frühstücken","to have breakfast",5,1],
    ["einkaufen","to go shopping",5,1],
    ["kochen","to cook",5,1],
    ["spazieren gehen","to go for a walk",5,1],
    ["aufräumen","to tidy up",5,1],
    ["aufstehen","to get up",5,1],
    ["gehen","to go",5,1],
    ["oder","or",5,5],
    ["müde","tired",5,2],
    ["anrufen","to call (phone)",5,1],
    ["früh","early",5,2],
    ["der Supermarkt","supermarket",5,0],
    ["fernsehen","to watch TV",5,1],
    ["mit","with",5,5],
    ["lange","for a long time",5,5],
    ["essen","to eat",5,1],
    ["gern","gladly, like to",5,5],
    // B — Uhrzeit
    ["spät","late",5,2],
    ["schon","already",5,5],
    ["erst","only (just)",5,5],
    ["das Viertel","quarter",5,0],
    ["vor","before",5,5],
    ["nach","after, past",5,5],
    ["halb","half",5,5],
    ["die Uhr","clock, o'clock",5,0],
    ["kurz","short, shortly",5,2],
    ["gleich","soon, right away",5,5],
    // C — Wochentage und Termine
    ["der Intensivkurs","intensive course",5,0],
    ["anfangen","to begin, start",5,1],
    ["am","on (day)",5,5],
    ["der Montag","Monday",5,0],
    ["der Dienstag","Tuesday",5,0],
    ["der Mittwoch","Wednesday",5,0],
    ["der Donnerstag","Thursday",5,0],
    ["der Freitag","Friday",5,0],
    ["der Samstag","Saturday",5,0],
    ["der Sonntag","Sunday",5,0],
    ["wann","when",5,3],
    ["um","at (time)",5,5],
    ["enden","to end",5,1],
    ["die Party","party",5,0],
    ["die Zeit","time",5,0],
    ["der Fußball","football, soccer",5,0],
    ["die Hausaufgabe","homework",5,0],
    ["die Mama","mom",5,0],
    ["schlafen","to sleep",5,1],
    ["das Wochenende","weekend",5,0],
    ["nächst","next",5,5],
    ["die Woche","week",5,0],
    // D — Tageszeiten
    ["der Morgen","morning",5,0],
    ["der Vormittag","late morning",5,0],
    ["der Mittag","noon, midday",5,0],
    ["der Nachmittag","afternoon",5,0],
    ["der Abend","evening",5,0],
    ["die Nacht","night",5,0],
    ["das Kino","cinema",5,0],
    ["der Sport","sports",5,0],
    ["trinken","to drink",5,1],
    ["die Pizza","pizza",5,0],
    ["chatten","to chat (online)",5,1],
    // E — Öffnungszeiten
    ["geöffnet","open",5,2],
    ["der Termin","appointment",5,0],
    ["der Kindergarten","kindergarten",5,0],
    ["das Geschäft","shop, business",5,0],
    ["die Bibliothek","library",5,0],
    ["geschlossen","closed",5,2],
    ["öffnen","to open",5,1],
    ["schließen","to close",5,1],
    ["die Praxis","practice, doctor's office",5,0],
    ["der Tag","day",5,0],
    ["jed","every, each",5,3],
    ["die Kita","daycare",5,0],
    ["bringen","to bring",5,1],
    ["abholen","to pick up",5,1],
    ["mehr","more",5,5],
    ["das Beispiel","example",5,0],
    ["zum Beispiel","for example",5,4],
    ["wieder","again",5,5],
    ["der Freund","friend (m.)",5,0],
    ["die Freundin","friend (f.)",5,0],
    ["antworten","to answer",5,1],
    ["total","totally",5,5],
    // --- Redemittel (Useful Expressions) ---
    // Uhrzeit
    ["Wie spät ist es?","What time is it?",5,4],
    ["Es ist sieben Uhr.","It is seven o'clock.",5,4],
    ["Es ist acht Uhr dreißig.","It is eight thirty.",5,4],
    ["Es ist halb neun.","It is half past eight.",5,4],
    ["Ist es schon zwölf?","Is it twelve already?",5,4],
    ["Nein, es ist erst Viertel vor zwölf.","No, it's only a quarter to twelve.",5,4],
    ["Es ist kurz vor zwölf.","It's almost twelve.",5,4],
    ["Es ist gleich zwölf.","It's almost twelve.",5,4],
    ["Es ist kurz nach zwölf.","It's just past twelve.",5,4],
    ["Um wie viel Uhr gehst du ins Bett?","What time do you go to bed?",5,4],
    ["Um elf Uhr.","At eleven.",5,4],
    ["Um halb elf.","At half past ten.",5,4],
    // Öffnungszeiten
    ["Wann ist ... geöffnet?","When is ... open?",5,4],
    ["Von 7 Uhr 30 bis 17 Uhr.","From 7:30 to 5 pm.",5,4],
    ["Von Montag bis Freitag.","From Monday to Friday.",5,4],
    // Verabredung
    ["Ich mache am Freitag eine Party.","I'm having a party on Friday.",5,4],
    ["Hast du Zeit?","Do you have time?",5,4],
    ["Wann fängt die Party an?","When does the party start?",5,4],
    ["Um sieben Uhr.","At seven o'clock.",5,4],
    ["Das passt gut.","That works well.",5,4],
    ["Ich komme gern.","I'd love to come.",5,4],
    ["Da habe ich keine Zeit.","I don't have time then.",5,4],
    // Vorlieben
    ["Was machst du gern?","What do you like to do?",5,4],
    ["Was machst du nicht gern?","What do you not like to do?",5,4],
    ["Stehst du gern früh auf?","Do you like getting up early?",5,4],
    ["Ich stehe nicht gern früh auf.","I don't like getting up early.",5,4],
    ["Ich arbeite gern.","I like working.",5,4],
    // Strategien
    ["Stimmt.","That's right.",5,4],
    ["Ich glaube, ...","I think ...",5,4],
    ["ins Bett gehen","to go to bed",5,1],
    ["passen","to fit, suit",5,1],

    // ===== Cat 6: Lektion 6 — Freizeit =====
    // Foto-Hörgeschichte — Ausflug
    ["der Ausflug","trip, excursion",6,0],
    ["das Auto","car",6,0],
    ["wandern","to hike",6,1],
    ["das Picknick","picnic",6,0],
    ["die Gitarre","guitar",6,0],
    ["telefonieren","to make a phone call",6,1],
    ["das Wetter","weather",6,0],
    ["die Sonne","sun",6,0],
    ["scheinen","to shine",6,1],
    ["regnen","to rain",6,1],
    ["viele","many, much",6,3],
    ["die Wolke","cloud",6,0],
    ["los","to set off",6,5],
    ["vergessen","to forget",6,1],
    ["der Durst","thirst",6,0],
    // A — Wetter
    ["das Grad","degree",6,0],
    ["warm","warm",6,2],
    ["windig","windy",6,2],
    ["kalt","cold",6,2],
    ["schneien","to snow",6,1],
    ["bewölkt","cloudy",6,2],
    ["der Wetterbericht","weather report",6,0],
    ["die Mitte","middle, center",6,0],
    ["überall","everywhere",6,5],
    ["die Temperatur","temperature",6,0],
    ["steigen","to rise",6,1],
    ["sonnig","sunny",6,2],
    ["leicht","light, slightly",6,2],
    ["bleiben","to stay, remain",6,1],
    ["der Regen","rain",6,0],
    ["der Schnee","snow",6,0],
    ["plus","plus",6,5],
    ["minus","minus",6,5],
    ["das Radio","radio",6,0],
    ["das Internet","internet",6,0],
    ["der Sommer","summer",6,0],
    ["heiß","hot",6,2],
    ["der Frühling","spring",6,0],
    ["der Herbst","autumn, fall",6,0],
    ["schlecht","bad",6,2],
    ["der Winter","winter",6,0],
    ["der Wind","wind",6,0],
    ["angenehm","pleasant",6,2],
    // B — Essen und Trinken
    ["die Speisekarte","menu",6,0],
    ["der Hamburger","hamburger",6,0],
    ["die Speise","dish, food",6,0],
    ["die Pommes frites","French fries",6,0],
    ["die Portion","portion",6,0],
    ["der Ketchup","ketchup",6,0],
    ["der Salat","salad",6,0],
    ["der Schinken","ham",6,0],
    ["das Getränk","drink, beverage",6,0],
    ["die Cola","cola",6,0],
    // C — Am Imbiss
    ["doch","yes (contradicting)",6,4],
    ["lieber","rather, prefer",6,5],
    ["nehmen","to take",6,1],
    ["warum","why",6,3],
    ["der Hund","dog",6,0],
    ["das Eis","ice cream",6,0],
    // D — Hobbys und Freizeit
    ["tanzen","to dance",6,1],
    ["schwimmen","to swim",6,1],
    ["treffen","to meet",6,1],
    ["das Fahrrad","bicycle",6,0],
    ["fahren","to drive, ride",6,1],
    ["grillen","to barbecue, grill",6,1],
    ["die Freizeit","free time, leisure",6,0],
    ["das Hobby","hobby",6,0],
    ["der Krimi","crime novel/movie",6,0],
    ["Lieblings","favorite",6,5],
    ["der Film","film, movie",6,0],
    ["wichtig","important",6,2],
    ["der Grill","grill",6,0],
    // E — Besondere Hobbys
    ["sammeln","to collect",6,1],
    ["der Beruf","profession, job",6,0],
    ["das Foto","photo",6,0],
    ["besonders","especially",6,5],
    ["fotografieren","to take photos",6,1],
    ["der Spaß","fun",6,0],
    ["das Smartphone","smartphone",6,0],
    ["dumm","stupid, silly",6,2],
    ["oft","often",6,5],
    ["das Spiel","game",6,0],
    ["leider","unfortunately",6,5],
    ["das Problem","problem",6,0],
    ["immer","always",6,5],
    ["vielleicht","maybe, perhaps",6,5],
    ["einfach","simple, easy",6,2],
    ["schnell","fast, quickly",6,2],
    // --- Redemittel (Useful Expressions) ---
    // Hobbys
    ["Was sind deine Hobbys?","What are your hobbies? (informal)",6,4],
    ["Was sind Ihre Hobbys?","What are your hobbies? (formal)",6,4],
    ["Meine Hobbys sind Lesen und Gitarre spielen.","My hobbies are reading and playing guitar.",6,4],
    ["Was machst du gern in der Freizeit?","What do you like to do in your free time? (informal)",6,4],
    ["Was machen Sie gern in der Freizeit?","What do you like to do in your free time? (formal)",6,4],
    ["Ich schwimme viel.","I swim a lot.",6,4],
    ["Ich tanze gern.","I like to dance.",6,4],
    ["Das macht Spaß.","That's fun.",6,4],
    ["Ich mache gern Sport.","I like doing sports.",6,4],
    ["Ich finde Krimis gut.","I think crime novels are good.",6,4],
    ["Ich finde Krimis toll.","I think crime novels are great.",6,4],
    ["Ich finde Krimis interessant.","I think crime novels are interesting.",6,4],
    // Vorlieben
    ["Mein Lieblingsbuch ist ...","My favorite book is ...",6,4],
    ["Mein Lieblingsfilm ist ...","My favorite film is ...",6,4],
    ["Mein Lieblingsspiel ist ...","My favorite game is ...",6,4],
    ["Meine Lieblingsmusik ist ...","My favorite music is ...",6,4],
    // Das Wetter
    ["Wie ist das Wetter?","What's the weather like?",6,4],
    ["Die Sonne scheint.","The sun is shining.",6,4],
    ["Es ist warm.","It's warm.",6,4],
    ["Es ist heiß.","It's hot.",6,4],
    ["Es ist kalt.","It's cold.",6,4],
    ["Es ist windig.","It's windy.",6,4],
    ["Es ist bewölkt.","It's cloudy.",6,4],
    ["Es gibt viele Wolken.","There are many clouds.",6,4],
    ["Es schneit.","It's snowing.",6,4],
    ["Es regnet.","It's raining.",6,4],
    ["Heute sind es sieben Grad.","Today it's seven degrees.",6,4],
    ["Im Sommer ist das Wetter sehr gut.","In summer the weather is very nice.",6,4],
    ["Was ist dein Lieblingswetter?","What is your favorite weather? (informal)",6,4],
    ["Was ist Ihr Lieblingswetter?","What is your favorite weather? (formal)",6,4],
    ["Ich finde warme Tage gut.","I like warm days.",6,4],
    ["Ich finde kalte Tage gut.","I like cold days.",6,4],
    ["Ich mag Wind.","I like wind.",6,4],
    ["Regen mag ich gar nicht.","I don't like rain at all.",6,4],
    // Strategien
    ["Guck mal!","Look!",6,4],
    ["Na klar!","Of course!",6,4],
    ["Na gut.","All right.",6,4],
    ["Oh, wie dumm!","Oh, how silly!",6,4],
    ["Kein Problem.","No problem.",6,4],
    ["Ich weiß nicht.","I don't know.",6,4],
    ["Moment mal, ...","Wait a moment, ...",6,4],
    ["mögen","to like",6,1],
    ["das Lieblingsbuch","favorite book",6,0],
    ["das Lieblingswetter","favorite weather",6,0],

    // ===== Cat 7: Lektion 7 — Kinder und Schule =====
    // Foto-Hörgeschichte
    ["prima","great, excellent",7,2],
    ["das Team","team",7,0],
    ["wecken","to wake (someone) up",7,1],
    ["das Frühstück","breakfast",7,0],
    ["fertig","ready, finished",7,2],
    ["los sein","What's going on?",7,4],
    ["die Mathematik","mathematics",7,0],
    ["der Test","test",7,0],
    ["pünktlich","on time, punctual",7,2],
    ["auf jeden Fall","definitely",7,4],
    ["schmecken","to taste",7,1],
    ["nach Hause","home (direction)",7,4],
    ["die Schule","school",7,0],
    // A — Fähigkeiten: können
    ["können","can, to be able to",7,1],
    ["krank","sick, ill",7,2],
    ["der Arzt","doctor (m.)",7,0],
    ["die Ärztin","doctor (f.)",7,0],
    ["backen","to bake",7,1],
    ["singen","to sing",7,1],
    ["reiten","to ride (horse)",7,1],
    ["das Klavier","piano",7,0],
    ["malen","to paint, draw",7,1],
    ["der Ski","ski",7,0],
    ["das Tennis","tennis",7,0],
    // B — Absichten: wollen
    ["wollen","to want",7,1],
    ["endlich","finally",7,5],
    ["das Lied","song",7,0],
    ["üben","to practice",7,1],
    ["der Text","text",7,0],
    ["die Übung","exercise",7,0],
    ["der Brief","letter",7,0],
    ["das Diktat","dictation",7,0],
    // C — Perfekt
    ["das Buch","book",7,0],
    // D — Vorschläge
    ["schade","what a pity",7,4],
    ["der Kilometer","kilometer",7,0],
    // E — Schule und Kommunikation
    ["die Kommunikation","communication",7,0],
    ["lieb","dear",7,2],
    ["das Mädchen","girl",7,0],
    ["der Junge","boy",7,0],
    ["die Klasse","class",7,0],
    ["das Schwimmbad","swimming pool",7,0],
    ["der Eintritt","admission, entry",7,0],
    ["losfahren","to depart, leave",7,1],
    ["zurückkommen","to come back",7,1],
    ["die Grundschule","elementary school",7,0],
    ["mitkommen","to come along",7,1],
    ["der Unterricht","class, lesson",7,0],
    ["leidtun","to be sorry",7,1],
    // --- Redemittel (Useful Expressions) ---
    // Starker Wunsch
    ["Was willst du lernen?","What do you want to learn? (informal)",7,4],
    ["Was wollen Sie lernen?","What do you want to learn? (formal)",7,4],
    ["Ich will Jonglieren lernen.","I want to learn to juggle.",7,4],
    ["Ich will gut Deutsch lernen.","I want to learn German well.",7,4],
    // Vorschlag
    ["Wollen wir Fahrrad fahren?","Shall we go cycling?",7,4],
    ["Wollen wir schwimmen gehen?","Shall we go swimming?",7,4],
    // Fähigkeit
    ["Ich kann sehr gut Ski fahren.","I can ski very well.",7,4],
    ["Kannst du Ski fahren?","Can you ski? (informal)",7,4],
    ["Können Sie Ski fahren?","Can you ski? (formal)",7,4],
    ["Ja, ich kann sehr gut Ski fahren.","Yes, I can ski very well.",7,4],
    ["Ja, ich kann ein bisschen Ski fahren.","Yes, I can ski a bit.",7,4],
    ["Nein, ich kann nicht so gut Ski fahren.","No, I can't ski so well.",7,4],
    ["Nein, ich kann gar nicht Ski fahren.","No, I can't ski at all.",7,4],
    ["Nein, nicht so gut.","No, not so well.",7,4],
    // Sich entschuldigen
    ["Ich bin krank.","I am sick.",7,4],
    ["Oh, das tut mir leid.","Oh, I'm sorry to hear that.",7,4],
    ["Mein Kind ist krank.","My child is sick.",7,4],
    ["Mein Sohn ist krank.","My son is sick.",7,4],
    ["Meine Tochter ist krank.","My daughter is sick.",7,4],
    ["Ich kann heute nicht zum Deutschkurs kommen.","I can't come to German class today.",7,4],
    ["Ich kann heute leider nicht zum Unterricht kommen.","Unfortunately I can't come to class today.",7,4],
    ["Ich sage es der Lehrerin.","I'll tell the teacher (f.).",7,4],
    ["Ich sage es dem Lehrer.","I'll tell the teacher (m.).",7,4],
    ["Ich gehe zum Arzt.","I'm going to the doctor.",7,4],
    ["Gute Besserung!","Get well soon!",7,4],
    // Über die Vergangenheit sprechen
    ["Das habe ich gestern gemacht.","I did this yesterday.",7,4],
    ["Gestern habe ich gearbeitet.","Yesterday I worked.",7,4],
    ["Am Wochenende bin ich Fahrrad gefahren.","On the weekend I went cycling.",7,4],
    ["Lara hat Tee gemacht.","Lara made tea.",7,4],
    ["Ich bin spazieren gegangen.","I went for a walk.",7,4],
    ["Bist du pünktlich gekommen?","Did you arrive on time?",7,4],
    // Strategien
    ["Ja, super!","Yes, great!",7,4],
    ["Nein, nicht so gern.","No, not really.",7,4],
    ["Schade!","What a pity!",7,4],
    ["gestern","yesterday",7,5],
    ["früher","earlier, before",7,5],
    ["die Lehrerin","teacher (f.)",7,0],
    ["der Lehrer","teacher (m.)",7,0],
    ["der Deutschkurs","German class",7,0],
    ["jonglieren","to juggle",7,1],
  ],
  // Batches are auto-generated below (groups of 8 within each Lektion)
  batches: [] as number[][],
};

// Build batches: 8 Lektion words per batch, partitioned by Lektion (no cross-Lektion
// batches). The 33 Anweisungen im Kurs (cat 0) are distributed one per batch across
// the first 33 Lektion batches so they're absorbed gradually instead of hit as a
// demotivating wall up front.
(function buildBatches() {
  var anweisungen: number[] = [];
  var byCat: {[k: number]: number[]} = {};
  VOCAB_A11_DATA.words.forEach(function(w, i) {
    var ci = w[2] as number;
    if (ci === 0) { anweisungen.push(i); return; }
    if (!byCat[ci]) byCat[ci] = [];
    byCat[ci].push(i);
  });
  var batches: number[][] = [];
  Object.keys(byCat).sort(function(a, b) { return Number(a) - Number(b); }).forEach(function(ci) {
    var indices = byCat[Number(ci)];
    for (var i = 0; i < indices.length; i += 8) {
      batches.push(indices.slice(i, i + 8));
    }
  });
  // Append one Anweisung to each of the first N batches
  anweisungen.forEach(function(wi, k) {
    if (batches[k]) batches[k].push(wi);
  });
  VOCAB_A11_DATA.batches = batches;
})();
