// Schritte Plus Neu A1.1 — Vocabulary
// Source: Schritte Plus Neu A1.1 textbook (Hueber)
// Organized by Lektion (lesson) per the book's structure
// English translations reused from VOCAB_DATA where overlapping, otherwise from PDF

// Word shape: [german, english, catIdx, typeIdx]
// catIdx: 0 = Anweisungen im Kurs, 1-7 = Lektion 1-7
// typeIdx: 0 = Noun, 1 = Verb, 2 = Adjective, 3 = Grammar, 4 = Expression, 5 = Foundational

export const VOCAB_A11_DATA = {
  cats: [
    "Anweisungen im Kurs",
    "Lektion 1: Guten Tag",
    "Lektion 2: Meine Familie",
    "Lektion 3: Einkaufen",
    "Lektion 4: Meine Wohnung",
    "Lektion 5: Mein Tag",
    "Lektion 6: Freizeit",
    "Lektion 7: Kinder und Schule",
    "Lektion 8: Beruf und Arbeit",
    "Lektion 9: Ämter und Behörden",
    "Lektion 10: Gesundheit und Krankheit",
    "Lektion 11: In der Stadt unterwegs",
    "Lektion 12: Kundenservice",
    "Lektion 13: Neue Kleider",
    "Lektion 14: Feste"
  ],
  types: ["Noun","Verb","Adjective","Grammar","Expression","Foundational"],
  words: [
    // ===== Cat 0: Anweisungen im Kurs (Classroom Instructions) =====
    ["ansehen","to look at",0,1],
    ["das Bild","picture, image",0,0],
    ["hören","to listen",0,1],
    ["noch einmal","once more, again",0,4],
    ["ankreuzen","to mark / check",0,1],
    ["zuordnen","to match, assign",0,1],
    ["ergänzen","to complete, fill in",0,1],
    ["machen","to make, do",0,1],
    ["der Kurs","course, class",0,0],
    ["sprechen","to speak",0,1],
    ["lesen","to read",0,1],
    ["das Gespräch","conversation, dialogue",0,0],
    ["spielen","to play, act out",0,1],
    ["suchen","to search, look for",0,1],
    ["zeigen","to show, point",0,1],
    ["fragen","to ask",0,1],
    ["markieren","to highlight, mark",0,1],
    ["die Frage","question",0,0],
    ["nachsprechen","to repeat (after sb.)",0,1],
    ["raten","to guess",0,1],
    ["das Wort","word",0,0],
    ["die Lektion","lesson",0,0],
    ["meinen","to mean, think",0,1],
    ["sagen","to say",0,1],
    ["notieren","to note down",0,1],
    ["vergleichen","to compare",0,1],
    ["schreiben","to write",0,1],
    ["variieren","to vary",0,1],
    ["erzählen","to tell, narrate",0,1],
    ["arbeiten","to work",0,1],
    ["zeichnen","to draw",0,1],
    ["verbinden","to connect",0,1],
    ["die Antwort","answer",0,0],

    // ===== Cat 1: Lektion 1 — Guten Tag =====
    // Foto-Hörgeschichte
    ["ich","I",1,3],
    ["heißen","to be called",1,1],
    ["der Name","name",1,0],
    ["kommen","to come",1,1],
    ["Deutschland","Germany",1,0],
    ["Deutsch","German (language)",1,0],
    ["und","and",1,5],
    ["ein bisschen","a little bit",1,4],
    // A — Begrüßung und Abschied
    ["Guten Tag","Good day / Hello",1,4],
    ["Hallo","Hello",1,4],
    ["Auf Wiedersehen","Goodbye",1,4],
    ["Tschüs","Bye (informal)",1,4],
    ["der Herr","Mr., gentleman",1,0],
    ["das Kind","child",1,0],
    ["Guten Abend","Good evening",1,4],
    ["die Dame","lady",1,0],
    ["willkommen","welcome",1,4],
    ["bei","at, with",1,5],
    ["die Musik","music",1,0],
    ["international","international",1,2],
    ["Guten Morgen","Good morning",1,4],
    ["die Frau","Mrs., woman, wife",1,0],
    ["danke","thank you",1,4],
    ["Gute Nacht","Good night",1,4],
    ["der Papa","dad",1,0],
    // B — Sich vorstellen
    ["sein","to be",1,1],
    ["Entschuldigung","excuse me, sorry",1,4],
    ["wie","how",1,3],
    ["Sie (formal)","you (formal)",1,3],
    ["wer","who",1,3],
    ["ja","yes",1,5],
    ["nein","no",1,5],
    // C — Herkunft und Sprachen
    ["woher","where from",1,3],
    ["aus","from",1,5],
    ["du","you (informal)",1,3],
    ["Österreich","Austria",1,0],
    ["die Schweiz","Switzerland",1,0],
    ["aha","I see!",1,4],
    ["toll","great, awesome",1,2],
    ["interessant","interesting",1,2],
    ["was","what",1,3],
    ["auch","also, too",1,5],
    ["die Sprache","language",1,0],
    // D — Buchstaben und Alphabet
    ["der Buchstabe","letter (of alphabet)",1,0],
    ["das Alphabet","alphabet",1,0],
    ["Wie bitte?","Pardon? Sorry?",1,4],
    ["buchstabieren","to spell",1,1],
    ["bitte","please",1,4],
    ["die Firma","company, firm",1,0],
    ["Vielen Dank","Thank you very much",1,4],
    ["Auf Wiederhören","Goodbye (on phone)",1,4],
    // E — Personalien
    ["die Adresse","address",1,0],
    ["die Visitenkarte","business card",1,0],
    ["der Vorname","first name",1,0],
    ["der Familienname","last name, surname",1,0],
    ["die Straße","street",1,0],
    ["die Stadt","city",1,0],
    ["das Land","country",1,0],
    ["die E-Mail","email",1,0],
    ["das Telefon","telephone",1,0],
    ["das Formular","form",1,0],
    ["die Fremdsprache","foreign language",1,0],
    ["die Anmeldung","registration",1,0],
    ["die Postleitzahl","zip code",1,0],
    // Länder und Sprachen
    ["Polen","Poland",1,0],
    ["die Türkei","Turkey",1,0],
    ["Spanien","Spain",1,0],
    ["Ungarn","Hungary",1,0],
    ["Rumänien","Romania",1,0],
    ["Syrien","Syria",1,0],
    ["Bulgarien","Bulgaria",1,0],
    ["Italien","Italy",1,0],
    ["Griechenland","Greece",1,0],
    // --- Redemittel (Useful Expressions) ---
    // Begrüßung
    ["(Herzlich) Willkommen.","(Warm) Welcome.",1,4],
    ["Freut mich.","Nice to meet you.",1,4],
    // Name
    ["Wie heißen Sie?","What is your name? (formal)",1,4],
    ["Wie heißt du?","What is your name? (informal)",1,4],
    ["Wer bist du?","Who are you? (informal)",1,4],
    ["Wer sind Sie?","Who are you? (formal)",1,4],
    ["Wie ist Ihr Name?","What is your name? (formal)",1,4],
    ["Wer ist das?","Who is that?",1,4],
    ["Ich heiße ...","My name is ...",1,4],
    ["Mein Name ist ...","My name is ...",1,4],
    ["Das ist Herr ...","This is Mr. ...",1,4],
    // Herkunft
    ["Woher kommen Sie?","Where are you from? (formal)",1,4],
    ["Woher kommst du?","Where are you from? (informal)",1,4],
    ["Ich komme aus ...","I come from ...",1,4],
    // Sprache
    ["Was sprechen Sie?","What languages do you speak? (formal)",1,4],
    ["Was sprichst du?","What languages do you speak? (informal)",1,4],
    ["Ich spreche Deutsch.","I speak German.",1,4],
    ["Sie sprechen gut Deutsch.","You speak German well. (formal)",1,4],
    ["Du sprichst gut Deutsch.","You speak German well. (informal)",1,4],
    ["Nur ein bisschen.","Just a little.",1,4],
    // Entschuldigung
    ["Tut mir leid.","I'm sorry.",1,4],
    // Bitten und Danken
    ["Ist Frau ... da, bitte?","Is Mrs. ... there, please?",1,4],
    ["Buchstabieren Sie, bitte.","Please spell that.",1,4],
    // Strategien
    ["Ja, stimmt.","Yes, that's right.",1,4],
    ["Ja, gut.","Yes, good.",1,4],
    ["Einen Moment, bitte.","One moment, please.",1,4],
    ["Ich weiß es nicht.","I don't know.",1,4],
    ["Ah, ja.","Oh, yes.",1,4],
    ["Aha!","I see!",1,4],
    ["Ah, schön.","Oh, nice.",1,4],
    ["Ah, toll.","Oh, great.",1,4],
    ["Interessant.","Interesting.",1,4],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["kennenlernen","to get to know, meet",1,1],
    ["danken","to thank",1,1],
    ["Vietnam","Vietnam",1,0],
    ["Thailand","Thailand",1,0],
    ["Frankreich","France",1,0],
    ["der Iran","Iran",1,0],

    // ===== Cat 2: Lektion 2 — Meine Familie =====
    // Foto-Hörgeschichte
    ["lernen","to learn",2,1],
    ["der Park","park",2,0],
    ["die Pause","break, pause",2,0],
    ["die Familie","family",2,0],
    ["der Vater","father",2,0],
    ["die Großeltern","grandparents",2,0],
    ["die Mutter","mother",2,0],
    ["die Eltern","parents",2,0],
    ["der Bruder","brother",2,0],
    ["die Geschwister","siblings",2,0],
    ["das Jahr","year",2,0],
    ["leben","to live",2,1],
    ["in","in",2,5],
    // A — Befinden
    ["gut","good, well",2,2],
    ["super","great, super",2,4],
    ["na ja","well... (hesitation)",2,4],
    ["ach","oh (expression)",2,4],
    ["so","so",2,5],
    ["sehr","very",2,5],
    // B — Familie
    ["der Enkel","grandson",2,0],
    ["die Enkelin","granddaughter",2,0],
    ["die Tochter","daughter",2,0],
    ["der Sohn","son",2,0],
    ["die Schwester","sister",2,0],
    ["die Oma","grandma",2,0],
    ["der Mann","man, husband",2,0],
    ["der Opa","grandpa",2,0],
    ["dein","your (informal)",2,3],
    ["mein","my",2,3],
    ["Ihr (formal)","your (formal)",2,3],
    ["der Ehemann","husband",2,0],
    ["die Ehefrau","wife",2,0],
    ["falsch","wrong, false",2,2],
    // C — Personalien
    ["sie","she",2,3],
    ["zusammen","together",2,5],
    ["geschieden","divorced",2,2],
    ["er","he",2,3],
    ["wohnen","to live, reside",2,1],
    ["jetzt","now",2,5],
    ["ihr","you (plural informal)",2,3],
    ["wir","we",2,3],
    // D — Zahlen und Personalien
    ["die Zahl","number",2,0],
    ["wo","where",2,3],
    ["geboren","born",2,2],
    ["die Nummer","number (phone)",2,0],
    ["verheiratet","married",2,2],
    ["haben","to have",2,1],
    ["der Geburtsort","place of birth",2,0],
    ["der Wohnort","place of residence",2,0],
    ["der Familienstand","marital status",2,0],
    ["ledig","single",2,2],
    ["verwitwet","widowed",2,2],
    ["das Alter","age",2,0],
    // E — Geografie
    ["der Norden","north",2,0],
    ["der Osten","east",2,0],
    ["der Süden","south",2,0],
    ["der Westen","west",2,0],
    ["die Hauptstadt","capital city",2,0],
    // --- Redemittel (Useful Expressions) ---
    // Befinden
    ["Wie geht's?","How are you?",2,4],
    ["Wie geht es Ihnen?","How are you? (formal)",2,4],
    ["Wie geht es dir?","How are you? (informal)",2,4],
    ["Und Ihnen?","And you? (formal)",2,4],
    ["Und dir?","And you? (informal)",2,4],
    ["Sehr gut, danke.","Very good, thanks.",2,4],
    ["Gut, danke.","Good, thanks.",2,4],
    ["Na ja, es geht.","Well, so-so.",2,4],
    ["Ach, nicht so gut.","Oh, not so good.",2,4],
    ["Auch gut, danke.","Also fine, thanks.",2,4],
    // Andere vorstellen
    ["Das ist mein Vater.","This is my father.",2,4],
    ["Das sind meine Großeltern.","These are my grandparents.",2,4],
    ["Er kommt aus ...","He comes from ...",2,4],
    ["Sie kommt aus ...","She comes from ...",2,4],
    ["Er lebt in ...","He lives in ...",2,4],
    ["Sie lebt in ...","She lives in ...",2,4],
    // Angaben zur Person
    ["Wo sind Sie geboren?","Where were you born?",2,4],
    ["Ich bin in ... geboren.","I was born in ...",2,4],
    ["Wo wohnen Sie?","Where do you live?",2,4],
    ["Ich wohne in ...","I live in ...",2,4],
    ["Wie ist Ihre Adresse?","What is your address?",2,4],
    ["Wie ist Ihre Telefonnummer?","What is your phone number?",2,4],
    ["Sind Sie verheiratet?","Are you married?",2,4],
    ["Ja, ich bin verheiratet.","Yes, I am married.",2,4],
    ["Nein, ich bin ledig.","No, I am single.",2,4],
    ["Haben Sie Kinder?","Do you have children?",2,4],
    ["Wie alt ist Ihr Kind?","How old is your child?",2,4],
    ["Wie alt sind Ihre Kinder?","How old are your children?",2,4],
    // Ort
    ["Hamburg liegt in Deutschland.","Hamburg is in Germany.",2,4],
    ["... ist die Hauptstadt von ...","... is the capital of ...",2,4],
    // Strategien
    ["Ja, genau.","Yes, exactly.",2,4],
    ["Nein, falsch.","No, wrong.",2,4],
    ["Na ja, ...","Well, ...",2,4],
    ["Ach, ...","Oh, ...",2,4],
    // Location & directions phrases
    ["Wo liegt...?","Where is... located?",2,4],
    ["Es liegt im Norden.","It is in the north.",2,4],
    ["Es liegt im Süden.","It is in the south.",2,4],
    ["im Norden","in the north",2,4],
    ["im Süden","in the south",2,4],
    ["im Westen","in the west",2,4],
    ["im Osten","in the east",2,4],
    // Additional family-context noun
    ["die Einladung","invitation",2,0],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["der Onkel","uncle",2,0],
    ["die Katze","cat",2,0],
    ["vertrauen","to trust",2,1],
    ["es","it",2,3],
    ["mich","me (accusative)",2,3],
    ["dich","you (accusative)",2,3],
    ["ihn","him (accusative)",2,3],
    ["uns","us (accusative/dative)",2,3],
    ["euch","you plural (accusative/dative)",2,3],
    ["mir","to me (dative)",2,3],
    ["dir","to you (dative)",2,3],
    ["ihm","to him, to it (dative)",2,3],
    ["ihnen","to them (dative)",2,3],

    // ===== Cat 3: Lektion 3 — Einkaufen =====
    // D — Preise und Mengenangaben
    ["der Preis","price",3,0],
    ["der Cent","cent",3,0],
    ["der Prospekt","brochure, flyer",3,0],
    ["das Sonderangebot","special offer",3,0],
    ["das Lebensmittel","food, groceries",3,0],
    ["wie viel","how much",3,4],
    ["kosten","to cost",3,1],
    ["das Kilo","kilogram",3,0],
    ["das Gramm","gram",3,0],
    ["das Pfund","pound (500g)",3,0],
    ["der Liter","liter",3,0],
    ["die Flasche","bottle",3,0],
    ["die Dose","can, tin",3,0],
    ["die Sahne","cream",3,0],
    ["die Wurst","sausage",3,0],
    ["das Hackfleisch","minced meat",3,0],
    // E — Einkaufen
    ["der Verkäufer","seller, shop assistant",3,0],
    ["die Verkäuferin","saleswoman, shop assistant (f.)",3,0],
    ["der Kunde","customer (m.)",3,0],
    ["die Kundin","customer (f.)",3,0],
    ["noch","still, also",3,5],
    ["alles","all, everything",3,3],
    ["möchten","would like",3,1],
    ["finden","to find",3,1],
    ["der Laden","shop, store",3,0],
    ["das Obst","fruit",3,0],
    ["das Gemüse","vegetables",3,0],
    ["die Bäckerei","bakery",3,0],
    ["das Rezept","recipe",3,0],
    ["das Wasser","water",3,0],
    ["der Pfeffer","pepper",3,0],
    // Lebensmittel
    ["die Schokolade","chocolate",3,0],
    ["die Milch","milk",3,0],
    ["der Käse","cheese",3,0],
    ["der Kuchen","cake",3,0],
    ["die Banane","banana",3,0],
    ["das Brot","bread",3,0],
    ["der Apfel","apple",3,0],
    ["die Orange","orange",3,0],
    ["die Butter","butter",3,0],
    ["der Fisch","fish",3,0],
    ["das Ei","egg",3,0],
    ["das Fleisch","meat",3,0],
    ["die Birne","pear",3,0],
    ["der Saft","juice",3,0],
    ["das Brötchen","bread roll",3,0],
    ["der Joghurt","yogurt",3,0],
    ["die Kartoffel","potato",3,0],
    ["die Zwiebel","onion",3,0],
    ["die Tomate","tomato",3,0],
    ["das Mineralwasser","mineral water",3,0],
    // --- Redemittel (Useful Expressions) ---
    // Nachfragen
    ["Was ist das?","What is that?",3,4],
    ["Das ist ein Apfel.","That is an apple.",3,4],
    ["Wie heißt das auf Deutsch?","What is that called in German?",3,4],
    ["Ist das ein Würstchen?","Is that a sausage?",3,4],
    ["Das stimmt.","That's right.",3,4],
    // Beim Einkaufen
    ["Kann ich Ihnen helfen?","Can I help you? (formal)",3,4],
    ["Kann ich dir helfen?","Can I help you? (informal)",3,4],
    ["Bitte schön?","Can I help you? / Here you go.",3,4],
    ["Wo finde ich ...?","Where can I find ...?",3,4],
    ["Ich hätte gern ...","I'd like ...",3,4],
    ["Ich möchte ...","I'd like ...",3,4],
    ["Haben Sie Eier?","Do you have eggs?",3,4],
    ["Wie viel möchten Sie?","How much do you want?",3,4],
    ["Wie viel kostet ein Kilo ...?","How much does a kilo of ... cost?",3,4],
    ["Wie viel kosten 100 Gramm ...?","How much does 100 grams of ... cost?",3,4],
    ["Das macht 2 Euro 50.","That comes to 2 Euro 50.",3,4],
    ["Hier, bitte.","Here you go.",3,4],
    ["Sonst noch etwas?","Anything else?",3,4],
    ["Ja, bitte.","Yes, please.",3,4],
    ["Nein, danke.","No, thanks.",3,4],
    ["Das ist alles.","That's all.",3,4],
    // Mengenangaben
    ["eine Flasche Saft","a bottle of juice",3,4],
    ["ein Liter Milch","a liter of milk",3,4],
    ["ein Pfund Brot","a pound of bread",3,4],
    ["eine Packung Tee","a package of tea",3,4],
    ["ein Becher Sahne","a cup of cream",3,4],
    ["ein Kilo Orangen","a kilo of oranges",3,4],
    ["eine Dose Tomaten","a can of tomatoes",3,4],
    // Strategien
    ["Ja, natürlich.","Yes, of course.",3,4],
    ["Nein, tut mir leid.","No, I'm sorry.",3,4],
    ["die Packung","package",3,0],
    ["der Becher","cup (container)",3,0],
    ["der Tee","tea",3,0],
    // Additional food & shopping vocabulary
    ["der Wein","wine",3,0],
    // Additional shopping vocab & phrases
    ["die Fleischtheke","meat counter",3,0],
    ["der Flohmarkt","flea market",3,0],
    ["das Schnäppchen","bargain",3,0],
    ["der Kaffee","coffee",3,0],
    ["günstig","reasonable, affordable",3,2],
    ["Ich hätte gern...","I would like...",3,4],
    ["Das macht... Euro.","That comes to... Euro.",3,4],
    ["Das wär's.","That's it.",3,4],
    ["Gern!","Gladly!",3,4],
    ["Was kostet...?","How much is...?",3,4],
    // Additional drinks, food & restaurant phrases
    ["der Orangensaft","orange juice",3,0],
    ["das Bier","beer",3,0],
    ["die Fanta","Fanta (soft drink)",3,0],
    ["das Würstchen","small sausage",3,0],
    ["ein Paar Würstchen","a pair of sausages",3,4],
    ["der Gemischte Salat","mixed salad",3,0],
    ["die Gulaschsuppe","goulash soup",3,0],
    ["die Portion Gemischtes Eis","portion of mixed ice cream",3,0],
    ["das Salz","salt",3,0],
    ["Was möchten Sie?","What would you like? (formal)",3,4],
    ["Zum Frühstück","for breakfast",3,4],
    ["Ich bringe ... sofort.","I'll bring ... right away.",3,4],
    ["Natürlich.","Of course.",3,4],
    // Additional baked goods & breads
    ["der Apfelkuchen","apple cake",3,0],
    ["der Pfannkuchen","pancake",3,0],
    ["das Mehl","flour",3,0],
    ["das Weißbrot","white bread",3,0],
    ["das Schwarzbrot","dark rye bread",3,0],
    // Additional shopping verbs
    ["helfen","to help",3,1],
    ["kaufen","to buy",3,1],
    ["geben","to give",3,1],
    // Additional gift / shopping noun
    ["das Geschenk","gift, present",3,0],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["brauchen","to need",3,1],
    ["die Suppe","soup",3,0],
    ["der Zucker","sugar",3,0],
    ["die Geldbörse","purse, wallet",3,0],
    ["der Geldbeutel","wallet",3,0],
    ["der Euro","euro",3,0],
    ["für","for (+ accusative)",3,5],
    ["ohne","without (+ accusative)",3,5],
    ["gegen","against (+ accusative)",3,5],

    // ===== Cat 4: Lektion 4 — Meine Wohnung =====
    // A — Wohnung
    ["die Wohnung","apartment",4,0],
    ["die Lampe","lamp",4,0],
    ["das Zimmer","room",4,0],
    ["die Küche","kitchen",4,0],
    ["das Bad","bathroom",4,0],
    ["alt","old",4,2],
    ["neu","new",4,2],
    ["groß","big, large",4,2],
    ["klein","small",4,2],
    ["hell","bright",4,2],
    ["dunkel","dark",4,2],
    ["teuer","expensive",4,2],
    ["billig","cheap",4,2],
    ["schön","beautiful, nice",4,2],
    ["hässlich","ugly",4,2],
    ["kennen","to know (person)",4,1],
    ["der Flur","hallway",4,0],
    ["die Toilette","toilet",4,0],
    ["der Balkon","balcony",4,0],
    ["das Wohnzimmer","living room",4,0],
    ["das Haus","house",4,0],
    ["hier","here",4,5],
    ["dort","there",4,5],
    // B — Beschreibung
    ["aber","but",4,5],
    ["nicht","not",4,5],
    ["der Monat","month",4,0],
    ["schmal","narrow",4,2],
    ["richtig","right, correct",4,2],
    ["breit","wide",4,2],
    // C — Möbel und Farben
    ["der Schrank","closet, cabinet",4,0],
    ["der Kühlschrank","refrigerator",4,0],
    ["das Sofa","sofa",4,0],
    ["der Tisch","table",4,0],
    ["der Stuhl","chair",4,0],
    ["das Bett","bed",4,0],
    ["der Fernseher","TV set",4,0],
    ["die Dusche","shower",4,0],
    ["der Herd","stove",4,0],
    ["die Badewanne","bathtub",4,0],
    ["der Teppich","carpet, rug",4,0],
    ["der Sessel","armchair",4,0],
    ["die Möbel","furniture",4,0],
    ["das Gerät","device, appliance",4,0],
    ["gefallen","to please, to like",4,1],
    ["die Farbe","color",4,0],
    ["ganz","whole, completely",4,5],
    ["modern","modern",4,2],
    ["schwarz","black",4,2],
    ["grau","gray",4,2],
    ["weiß","white",4,2],
    ["grün","green",4,2],
    ["braun","brown",4,2],
    ["blau","blue",4,2],
    ["rot","red",4,2],
    ["gelb","yellow",4,2],
    // D — Wohnungsanzeigen
    ["der Zentimeter","centimeter",4,0],
    ["mal","times (multiplication)",4,5],
    ["das Handy","mobile phone",4,0],
    ["die Arbeit","work",4,0],
    ["die Anzeige","advertisement",4,0],
    ["nett","nice",4,2],
    ["das Ehepaar","married couple",4,0],
    ["der Garten","garden",4,0],
    ["vermieten","to rent out",4,1],
    ["das Apartment","apartment",4,0],
    ["der Raum","room, space",4,0],
    ["der Stock","floor, story",4,0],
    ["circa","approximately",4,5],
    ["privat","private",4,2],
    ["ab","from",4,5],
    ["sofort","immediately",4,5],
    ["maximal","maximum",4,5],
    ["möbliert","furnished",4,2],
    ["die Garage","garage",4,0],
    ["der Quadratmeter","square meter",4,0],
    ["nur","only",4,5],
    ["die Miete","rent",4,0],
    ["bezahlen","to pay",4,1],
    // E — Kaufen und Verkaufen
    ["verkaufen","to sell",4,1],
    ["etwas","something",4,3],
    ["der Computer","computer",4,0],
    ["der Schreibtisch","desk",4,0],
    ["heute","today",4,5],
    ["welche","Which...?",4,3],
    ["also","so, well",4,5],
    ["ungefähr","approximately",4,5],
    ["der Meter","meter",4,0],
    ["lang","long",4,2],
    ["genau","exactly",4,5],
    ["sehen","to see",4,1],
    ["hoch","high, tall",4,2],
    ["morgen","tomorrow",4,5],
    ["das Regal","shelf",4,0],
    // --- Redemittel (Useful Expressions) ---
    // Gefallen/Missfallen
    ["Wie gefällt dir der Tisch?","How do you like the table? (informal)",4,4],
    ["Wie gefällt Ihnen der Tisch?","How do you like the table? (formal)",4,4],
    ["Wie gefallen dir die Betten?","How do you like the beds? (informal)",4,4],
    ["Wie gefallen Ihnen die Betten?","How do you like the beds? (formal)",4,4],
    ["Sehr gut.","Very good.",4,4],
    ["Ganz gut.","Quite good.",4,4],
    ["Es geht.","It's okay.",4,4],
    ["Nicht so gut.","Not so good.",4,4],
    // Nach dem Ort fragen
    ["Wo ist die Küche?","Where is the kitchen?",4,4],
    ["Ist das hier das Bad?","Is this the bathroom?",4,4],
    ["Ja, das hier ist das Bad.","Yes, this is the bathroom.",4,4],
    ["Ist hier auch ein Arbeitszimmer?","Is there also a study here?",4,4],
    // Beschreiben
    ["Wie ist dein Zimmer?","What is your room like?",4,4],
    ["Es ist teuer.","It's expensive.",4,4],
    ["Es ist nicht teuer.","It's not expensive.",4,4],
    ["Es ist sehr teuer.","It's very expensive.",4,4],
    ["Wie lang ist der Tisch?","How long is the table?",4,4],
    ["Wie breit ist der Tisch?","How wide is the table?",4,4],
    ["Wie hoch ist der Tisch?","How tall is the table?",4,4],
    ["Ungefähr zwei Meter.","Approximately two meters.",4,4],
    ["Genau zwei Meter.","Exactly two meters.",4,4],
    ["Wie groß ist das Bett?","How big is the bed?",4,4],
    ["Welche Farbe hat der Tisch?","What color is the table?",4,4],
    ["Er ist dunkelbraun.","It is dark brown.",4,4],
    // Ein Telefongespräch führen
    ["Sie verkaufen doch ...?","You're selling ..., right?",4,4],
    ["Ist der ... noch da?","Is the ... still available?",4,4],
    ["Wie alt ist er?","How old is it?",4,4],
    ["Was kostet er?","How much does it cost?",4,4],
    ["Und wo wohnen Sie, bitte?","And where do you live, please?",4,4],
    ["In der ... straße.","On ... street.",4,4],
    ["Sind Sie heute zu Hause?","Are you home today?",4,4],
    ["Sind Sie morgen zu Hause?","Are you home tomorrow?",4,4],
    ["Ja, ich bin da.","Yes, I'm home.",4,4],
    ["Nein, ich bin nicht da.","No, I'm not home.",4,4],
    // Strategien
    ["Sagen Sie mal, ...","Tell me, ... (formal)",4,4],
    ["Sag mal, ...","Tell me, ... (informal)",4,4],
    ["Ja, richtig.","Yes, right.",4,4],
    ["Aha, gut!","Oh, good!",4,4],
    ["..., nicht?","..., right?",4,4],
    ["..., oder?","..., or?",4,4],
    ["..., richtig?","..., correct?",4,4],
    ["Schau mal!","Look! (informal)",4,4],
    ["Schauen Sie mal!","Look! (formal)",4,4],
    ["dunkelbraun","dark brown",4,2],
    ["zu Hause","at home",4,4],
    // Additional rooms & housing adjectives
    ["das Schlafzimmer","bedroom",4,0],
    ["das Arbeitszimmer","study, home office",4,0],
    ["ruhig","quiet",4,2],
    ["laut","loud, noisy",4,2],
    ["altmodisch","old-fashioned",4,2],
    ["tief","deep",4,2],
    // Additional furniture & appliances
    ["der Spiegel","mirror",4,0],
    ["die Waschmaschine","washing machine",4,0],
    ["die Spülmaschine","dishwasher",4,0],
    // Negation grammar
    ["kein","no, not a (m./n.)",4,3],
    ["keine","no, not a (f./pl.)",4,3],
    ["Es gibt kein...","There is no...",4,4],
    // Additional furniture
    ["der Gartenstuhl","garden chair",4,0],
    // Additional conjunctions
    ["denn","because, for (coord.)",4,5],
    ["weil","because (subord.)",4,5],
    // Additional housing verbs
    ["mieten","to rent",4,1],
    ["tragen","to carry, wear",4,1],
    // Question words
    ["Wo?","Where?",4,3],
    ["Was?","What?",4,3],
    ["Wie?","How?",4,3],
    // Answer word
    ["Doch","Yes! (contradicting a negative)",4,5],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["der Nachbar","neighbour",4,0],
    ["die Wand","wall",4,0],
    ["das Holz","wood",4,0],

    // ===== Cat 5: Lektion 5 — Mein Tag =====
    // Foto-Hörgeschichte & A — Tagesablauf
    ["die Präsentation","presentation",5,0],
    ["frühstücken","to have breakfast",5,1],
    ["einkaufen","to go shopping",5,1],
    ["kochen","to cook",5,1],
    ["spazieren gehen","to go for a walk",5,1],
    ["aufräumen","to tidy up",5,1],
    ["aufstehen","to get up",5,1],
    ["gehen","to go",5,1],
    ["oder","or",5,5],
    ["müde","tired",5,2],
    ["anrufen","to call (phone)",5,1],
    ["früh","early",5,2],
    ["der Supermarkt","supermarket",5,0],
    ["fernsehen","to watch TV",5,1],
    ["mit","with",5,5],
    ["lange","for a long time",5,5],
    ["essen","to eat",5,1],
    ["gern","gladly, like to",5,5],
    // B — Uhrzeit
    ["spät","late",5,2],
    ["schon","already",5,5],
    ["erst","only (just)",5,5],
    ["das Viertel","quarter",5,0],
    ["vor","before",5,5],
    ["nach","after, past",5,5],
    ["halb","half",5,5],
    ["die Uhr","clock, o'clock",5,0],
    ["kurz","short, shortly",5,2],
    ["gleich","soon, right away",5,5],
    // C — Wochentage und Termine
    ["der Intensivkurs","intensive course",5,0],
    ["anfangen","to begin, start",5,1],
    ["am","on (day)",5,5],
    ["der Montag","Monday",5,0],
    ["der Dienstag","Tuesday",5,0],
    ["der Mittwoch","Wednesday",5,0],
    ["der Donnerstag","Thursday",5,0],
    ["der Freitag","Friday",5,0],
    ["der Samstag","Saturday",5,0],
    ["der Sonntag","Sunday",5,0],
    ["wann","when",5,3],
    ["um","at (time)",5,5],
    ["enden","to end",5,1],
    ["die Party","party",5,0],
    ["die Zeit","time",5,0],
    ["der Fußball","football, soccer",5,0],
    ["die Hausaufgabe","homework",5,0],
    ["die Mama","mom",5,0],
    ["schlafen","to sleep",5,1],
    ["das Wochenende","weekend",5,0],
    ["nächst","next",5,5],
    ["die Woche","week",5,0],
    // D — Tageszeiten
    ["der Morgen","morning",5,0],
    ["der Vormittag","late morning",5,0],
    ["der Mittag","noon, midday",5,0],
    ["der Nachmittag","afternoon",5,0],
    ["der Abend","evening",5,0],
    ["die Nacht","night",5,0],
    ["das Kino","cinema",5,0],
    ["der Sport","sports",5,0],
    ["trinken","to drink",5,1],
    ["die Pizza","pizza",5,0],
    ["chatten","to chat (online)",5,1],
    // E — Öffnungszeiten
    ["geöffnet","open",5,2],
    ["der Termin","appointment",5,0],
    ["der Kindergarten","kindergarten",5,0],
    ["das Geschäft","shop, business",5,0],
    ["die Bibliothek","library",5,0],
    ["geschlossen","closed",5,2],
    ["öffnen","to open",5,1],
    ["schließen","to close",5,1],
    ["die Praxis","practice, doctor's office",5,0],
    ["der Tag","day",5,0],
    ["jed","every, each",5,3],
    ["die Kita","daycare",5,0],
    ["bringen","to bring",5,1],
    ["abholen","to pick up",5,1],
    ["mehr","more",5,5],
    ["das Beispiel","example",5,0],
    ["zum Beispiel","for example",5,4],
    ["wieder","again",5,5],
    ["der Freund","friend (m.)",5,0],
    ["die Freundin","friend (f.)",5,0],
    ["antworten","to answer",5,1],
    ["total","totally",5,5],
    // --- Redemittel (Useful Expressions) ---
    // Uhrzeit
    ["Wie spät ist es?","What time is it?",5,4],
    ["Es ist sieben Uhr.","It is seven o'clock.",5,4],
    ["Es ist acht Uhr dreißig.","It is eight thirty.",5,4],
    ["Es ist halb neun.","It is half past eight.",5,4],
    ["Ist es schon zwölf?","Is it twelve already?",5,4],
    ["Nein, es ist erst Viertel vor zwölf.","No, it's only a quarter to twelve.",5,4],
    ["Es ist kurz vor zwölf.","It's almost twelve.",5,4],
    ["Es ist gleich zwölf.","It's almost twelve.",5,4],
    ["Es ist kurz nach zwölf.","It's just past twelve.",5,4],
    ["Um wie viel Uhr gehst du ins Bett?","What time do you go to bed?",5,4],
    ["Um elf Uhr.","At eleven.",5,4],
    ["Um halb elf.","At half past ten.",5,4],
    // Öffnungszeiten
    ["Wann ist ... geöffnet?","When is ... open?",5,4],
    ["Wann ist der Kindergarten geöffnet?","When is the kindergarten open?",5,4],
    ["Von 7 Uhr 30 bis 17 Uhr.","From 7:30 to 5 pm.",5,4],
    ["Von Montag bis Freitag.","From Monday to Friday.",5,4],
    // Verabredung
    ["Ich mache am Freitag eine Party.","I'm having a party on Friday.",5,4],
    ["Hast du Zeit?","Do you have time?",5,4],
    ["Wann fängt die Party an?","When does the party start?",5,4],
    ["Um sieben Uhr.","At seven o'clock.",5,4],
    ["Das passt gut.","That works well.",5,4],
    ["Ich komme gern.","I'd love to come.",5,4],
    ["Da habe ich keine Zeit.","I don't have time then.",5,4],
    // Vorlieben
    ["Was machst du gern?","What do you like to do?",5,4],
    ["Was machst du nicht gern?","What do you not like to do?",5,4],
    ["Stehst du gern früh auf?","Do you like getting up early?",5,4],
    ["Ich stehe nicht gern früh auf.","I don't like getting up early.",5,4],
    ["Ich arbeite gern.","I like working.",5,4],
    // Strategien
    ["Stimmt.","That's right.",5,4],
    ["Ich glaube, ...","I think ...",5,4],
    ["ins Bett gehen","to go to bed",5,1],
    ["passen","to fit, suit",5,1],
    // Additional separable verbs
    ["anmachen","to turn on",5,1],
    ["ausschalten","to switch off",5,1],
    ["anmelden","to sign up, register",5,1],
    ["abschließen","to lock, close",5,1],
    ["ausfüllen","to fill out (a form)",5,1],
    ["abschreiben","to copy down",5,1],
    ["aussehen","to look (like)",5,1],
    ["ankommen","to arrive",5,1],
    ["ausmachen","to turn off, agree on",5,1],
    ["umziehen","to move (house), change clothes",5,1],
    ["aufmachen","to open",5,1],
    // Additional regular verbs
    ["erklären","to explain",5,1],
    ["übersetzen","to translate",5,1],
    ["bearbeiten","to edit, process",5,1],
    ["wiederholen","to repeat, review",5,1],
    // Computer course nouns
    ["der Computerkurs","computer course",5,0],
    ["die Kursleiterin","course instructor (f.)",5,0],
    ["der Teilnehmer","participant (m.)",5,0],
    ["das Programm","program",5,0],
    ["das Netz","network, internet",5,0],
    ["der Computerraum","computer room",5,0],
    // Time expressions
    ["sonntags","on Sundays",5,5],
    ["manchmal","sometimes",5,5],
    ["abends","in the evening",5,5],
    ["jede Woche","every week",5,4],
    ["heute Abend","tonight, this evening",5,4],
    // More daily-routine verbs & time vocabulary
    ["aufhängen","to hang up",5,1],
    ["ausleeren","to empty out",5,1],
    ["anziehen","to put on, dress",5,1],
    ["zumachen","to close",5,1],
    ["ausgehen","to go out",5,1],
    ["putzen","to clean",5,1],
    ["Viertel","quarter (15 min)",5,5],
    ["kurz vor","shortly before",5,4],
    ["kurz nach","shortly after",5,4],
    ["von...bis","from...to",5,4],
    ["seit","since, for",5,5],
    ["im","in (month/season)",5,5],
    // Time of day & time-telling
    ["am Morgen","in the morning",5,4],
    ["am Vormittag","in the late morning",5,4],
    ["am Mittag","at noon",5,4],
    ["am Nachmittag","in the afternoon",5,4],
    ["am Abend","in the evening",5,4],
    ["in der Nacht","at night",5,4],
    ["der ganze Tag","the whole day",5,4],
    ["Es ist... Uhr","It is... o'clock",5,4],
    ["Viertel nach","quarter past",5,4],
    ["Viertel vor","quarter to",5,4],
    ["Von wann bis wann...?","From when to when...?",5,4],
    // Additional adverbs of liking (intensifiers for gern)
    ["sehr gern","very much (like to)",5,5],
    ["total gern","really love to (colloquial)",5,5],
    // Additional time words & connectors
    ["dann","then",5,5],
    ["danach","after that",5,5],
    ["schon einmal","once before, already",5,5],
    ["Wann?","When?",5,3],
    ["Warum?","Why?",5,3],
    // Time expressions with prepositions
    ["um 6 Uhr","at 6 o'clock",5,4],
    ["um 12 Uhr / 13 Uhr","at 12 / 1 o'clock",5,4],
    ["bis 17 Uhr","until 5 pm",5,4],
    ["im Mai","in May",5,4],
    ["für zwei Wochen","for two weeks",5,4],
    ["fast drei Jahre","almost three years",5,4],
    // Daily routine verbs
    ["duschen","to shower",5,1],
    ["schicken","to send",5,1],
    ["hinbringen","to take (s.o./s.th.) there",5,1],
    ["hinfahren","to drive / go there",5,1],
    ["checken","to check",5,1],
    // Daily-life nouns
    ["die Tomatensoße","tomato sauce",5,0],
    ["der Lkw-Fahrer","truck driver",5,0],
    ["der Krieg","war",5,0],
    ["die Blumenstraße","Blumen Street (street name)",5,0],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["jeden Tag","every day",5,4],
    ["von","from, of (+ dative)",5,5],
    ["zu","to (+ dative)",5,5],

    // ===== Cat 6: Lektion 6 — Freizeit =====
    // Foto-Hörgeschichte — Ausflug
    ["der Ausflug","trip, excursion",6,0],
    ["das Auto","car",6,0],
    ["wandern","to hike",6,1],
    ["das Picknick","picnic",6,0],
    ["die Gitarre","guitar",6,0],
    ["telefonieren","to make a phone call",6,1],
    ["das Wetter","weather",6,0],
    ["die Sonne","sun",6,0],
    ["scheinen","to shine",6,1],
    ["regnen","to rain",6,1],
    ["viele","many, much",6,3],
    ["die Wolke","cloud",6,0],
    ["los","to set off",6,5],
    ["vergessen","to forget",6,1],
    ["der Durst","thirst",6,0],
    // A — Wetter
    ["das Grad","degree",6,0],
    ["warm","warm",6,2],
    ["windig","windy",6,2],
    ["kalt","cold",6,2],
    ["schneien","to snow",6,1],
    ["bewölkt","cloudy",6,2],
    ["der Wetterbericht","weather report",6,0],
    ["die Mitte","middle, center",6,0],
    ["überall","everywhere",6,5],
    ["die Temperatur","temperature",6,0],
    ["steigen","to rise",6,1],
    ["sonnig","sunny",6,2],
    ["leicht","light, slightly",6,2],
    ["bleiben","to stay, remain",6,1],
    ["der Regen","rain",6,0],
    ["der Schnee","snow",6,0],
    ["plus","plus",6,5],
    ["minus","minus",6,5],
    ["das Radio","radio",6,0],
    ["das Internet","internet",6,0],
    ["der Sommer","summer",6,0],
    ["heiß","hot",6,2],
    ["der Frühling","spring",6,0],
    ["der Herbst","autumn, fall",6,0],
    ["schlecht","bad",6,2],
    ["der Winter","winter",6,0],
    ["der Wind","wind",6,0],
    ["angenehm","pleasant",6,2],
    // B — Essen und Trinken
    ["die Speisekarte","menu",6,0],
    ["der Hamburger","hamburger",6,0],
    ["die Speise","dish, food",6,0],
    ["die Pommes frites","French fries",6,0],
    ["die Portion","portion",6,0],
    ["der Ketchup","ketchup",6,0],
    ["der Salat","salad",6,0],
    ["der Schinken","ham",6,0],
    ["das Getränk","drink, beverage",6,0],
    ["die Cola","cola",6,0],
    // C — Am Imbiss
    ["lieber","rather, prefer",6,5],
    ["nehmen","to take",6,1],
    ["warum","why",6,3],
    ["der Hund","dog",6,0],
    ["das Eis","ice cream",6,0],
    // D — Hobbys und Freizeit
    ["tanzen","to dance",6,1],
    ["schwimmen","to swim",6,1],
    ["treffen","to meet",6,1],
    ["das Fahrrad","bicycle",6,0],
    ["fahren","to drive, ride",6,1],
    ["grillen","to barbecue, grill",6,1],
    ["die Freizeit","free time, leisure",6,0],
    ["das Hobby","hobby",6,0],
    ["der Krimi","crime novel/movie",6,0],
    ["Lieblings","favorite",6,5],
    ["der Film","film, movie",6,0],
    ["wichtig","important",6,2],
    ["der Grill","grill",6,0],
    // E — Besondere Hobbys
    ["sammeln","to collect",6,1],
    ["der Beruf","profession, job",6,0],
    ["das Foto","photo",6,0],
    ["besonders","especially",6,5],
    ["fotografieren","to take photos",6,1],
    ["der Spaß","fun",6,0],
    ["das Smartphone","smartphone",6,0],
    ["dumm","stupid, silly",6,2],
    ["oft","often",6,5],
    ["das Spiel","game",6,0],
    ["leider","unfortunately",6,5],
    ["das Problem","problem",6,0],
    ["immer","always",6,5],
    ["vielleicht","maybe, perhaps",6,5],
    ["einfach","simple, easy",6,2],
    ["schnell","fast, quickly",6,2],
    // --- Redemittel (Useful Expressions) ---
    // Hobbys
    ["Was sind deine Hobbys?","What are your hobbies? (informal)",6,4],
    ["Was sind Ihre Hobbys?","What are your hobbies? (formal)",6,4],
    ["Meine Hobbys sind Lesen und Gitarre spielen.","My hobbies are reading and playing guitar.",6,4],
    ["Was machst du gern in der Freizeit?","What do you like to do in your free time? (informal)",6,4],
    ["Was machen Sie gern in der Freizeit?","What do you like to do in your free time? (formal)",6,4],
    ["Ich schwimme viel.","I swim a lot.",6,4],
    ["Ich tanze gern.","I like to dance.",6,4],
    ["Das macht Spaß.","That's fun.",6,4],
    ["Ich mache gern Sport.","I like doing sports.",6,4],
    ["Ich finde Krimis gut.","I think crime novels are good.",6,4],
    ["Ich finde Krimis toll.","I think crime novels are great.",6,4],
    ["Ich finde Krimis interessant.","I think crime novels are interesting.",6,4],
    // Vorlieben
    ["Mein Lieblingsbuch ist ...","My favorite book is ...",6,4],
    ["Mein Lieblingsfilm ist ...","My favorite film is ...",6,4],
    ["Mein Lieblingsspiel ist ...","My favorite game is ...",6,4],
    ["Meine Lieblingsmusik ist ...","My favorite music is ...",6,4],
    // Das Wetter
    ["Wie ist das Wetter?","What's the weather like?",6,4],
    ["Die Sonne scheint.","The sun is shining.",6,4],
    ["Es ist warm.","It's warm.",6,4],
    ["Es ist heiß.","It's hot.",6,4],
    ["Es ist kalt.","It's cold.",6,4],
    ["Es ist windig.","It's windy.",6,4],
    ["Es ist bewölkt.","It's cloudy.",6,4],
    ["Es gibt viele Wolken.","There are many clouds.",6,4],
    ["Es schneit.","It's snowing.",6,4],
    ["Es regnet.","It's raining.",6,4],
    ["Heute sind es sieben Grad.","Today it's seven degrees.",6,4],
    ["Im Sommer ist das Wetter sehr gut.","In summer the weather is very nice.",6,4],
    ["Was ist dein Lieblingswetter?","What is your favorite weather? (informal)",6,4],
    ["Was ist Ihr Lieblingswetter?","What is your favorite weather? (formal)",6,4],
    ["Ich finde warme Tage gut.","I like warm days.",6,4],
    ["Ich finde kalte Tage gut.","I like cold days.",6,4],
    ["Ich mag Wind.","I like wind.",6,4],
    ["Regen mag ich gar nicht.","I don't like rain at all.",6,4],
    // Strategien
    ["Guck mal!","Look!",6,4],
    ["Na klar!","Of course!",6,4],
    ["Na gut.","All right.",6,4],
    ["Oh, wie dumm!","Oh, how silly!",6,4],
    ["Hm, ...","Hmm, ...",6,4],
    ["Kein Problem.","No problem.",6,4],
    ["Ich weiß nicht.","I don't know.",6,4],
    ["Moment mal, ...","Wait a moment, ...",6,4],
    ["mögen","to like",6,1],
    ["das Lieblingsbuch","favorite book",6,0],
    ["das Lieblingswetter","favorite weather",6,0],
    // Additional leisure & travel nouns
    ["der Urlaub","vacation, holiday",6,0],
    ["der Zug","train",6,0],
    ["der Kiosk","kiosk, newsstand",6,0],
    // Months
    ["Januar","January",6,5],
    ["Februar","February",6,5],
    ["März","March",6,5],
    ["April","April",6,5],
    ["Mai","May",6,5],
    ["Juni","June",6,5],
    ["Juli","July",6,5],
    ["August","August",6,5],
    ["September","September",6,5],
    ["Oktober","October",6,5],
    ["November","November",6,5],
    ["Dezember","December",6,5],
    // Leisure phrases
    ["Ich habe keine Zeit.","I have no time.",6,4],
    ["Wie gefällt dir...?","How do you like...?",6,4],
    // Additional weather vocabulary
    ["der Nebel","fog",6,0],
    ["das Gewitter","thunderstorm",6,0],
    ["es regnet","it is raining",6,4],
    ["es schneit","it is snowing",6,4],
    ["es ist bewölkt","it is cloudy",6,4],
    ["es ist kalt","it is cold",6,4],
    ["es ist warm","it is warm",6,4],
    ["es ist windig","it is windy",6,4],
    ["die Sonne scheint","the sun shines",6,4],
    ["es sind ... Grad","it is ... degrees",6,4],
    ["unter Null","below zero",6,4],
    ["über Null","above zero",6,4],
    // Additional weather & geography
    ["leicht bewölkt","partly cloudy",6,4],
    ["die Küste","coast",6,0],
    ["das Landesinnere","inland, interior",6,0],
    ["bis zu 20 Grad","up to 20 degrees",6,4],
    ["minus zwei Grad","minus two degrees",6,4],
    ["um die 25 Grad","around 25 degrees",6,4],
    // Additional hobby & leisure vocabulary
    ["das Computerspiel","computer game",6,0],
    ["der Satz","sentence",6,0],
    ["die Lieblingsfarbe","favorite color",6,0],
    ["das Lieblingsessen","favorite food",6,0],
    ["die Lieblingsmusik","favorite music",6,0],
    ["surfen","to surf (internet)",6,1],
    ["feiern","to celebrate",6,1],
    ["informieren","to inform",6,1],
    ["leider nicht","unfortunately not",6,4],
    ["Kommt sofort.","Coming right up.",6,4],
    ["Ja, gern.","Yes, gladly.",6,4],
    ["oder?","...right? (tag question)",6,4],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["leihen","to lend",6,1],
    ["springen","to jump",6,1],
    ["laufen","to run, to walk",6,1],
    ["kämpfen","to fight",6,1],
    ["der Ball","ball",6,0],

    // ===== Cat 7: Lektion 7 — Kinder und Schule =====
    // Foto-Hörgeschichte
    ["prima","great, excellent",7,2],
    ["das Team","team",7,0],
    ["wecken","to wake (someone) up",7,1],
    ["das Frühstück","breakfast",7,0],
    ["fertig","ready, finished",7,2],
    ["los sein","What's going on?",7,4],
    ["die Mathematik","mathematics",7,0],
    ["der Test","test",7,0],
    ["pünktlich","on time, punctual",7,2],
    ["auf jeden Fall","definitely",7,4],
    ["schmecken","to taste",7,1],
    ["nach Hause","home (direction)",7,4],
    ["die Schule","school",7,0],
    // A — Fähigkeiten: können
    ["können","can, to be able to",7,1],
    ["krank","sick, ill",7,2],
    ["der Arzt","doctor (m.)",7,0],
    ["die Ärztin","doctor (f.)",7,0],
    ["backen","to bake",7,1],
    ["singen","to sing",7,1],
    ["reiten","to ride (horse)",7,1],
    ["das Klavier","piano",7,0],
    ["malen","to paint, draw",7,1],
    ["der Ski","ski",7,0],
    ["das Tennis","tennis",7,0],
    // B — Absichten: wollen
    ["wollen","to want",7,1],
    ["endlich","finally",7,5],
    ["das Lied","song",7,0],
    ["üben","to practice",7,1],
    ["der Text","text",7,0],
    ["die Übung","exercise",7,0],
    ["der Brief","letter",7,0],
    ["das Diktat","dictation",7,0],
    // C — Perfekt
    ["das Buch","book",7,0],
    // D — Vorschläge
    ["schade","what a pity",7,4],
    ["der Kilometer","kilometer",7,0],
    // E — Schule und Kommunikation
    ["die Kommunikation","communication",7,0],
    ["lieb","dear",7,2],
    ["das Mädchen","girl",7,0],
    ["der Junge","boy",7,0],
    ["die Klasse","class",7,0],
    ["das Schwimmbad","swimming pool",7,0],
    ["der Eintritt","admission, entry",7,0],
    ["losfahren","to depart, leave",7,1],
    ["zurückkommen","to come back",7,1],
    ["die Grundschule","elementary school",7,0],
    ["mitkommen","to come along",7,1],
    ["der Unterricht","class, lesson",7,0],
    ["leidtun","to be sorry",7,1],
    // --- Redemittel (Useful Expressions) ---
    // Starker Wunsch
    ["Was willst du lernen?","What do you want to learn? (informal)",7,4],
    ["Was wollen Sie lernen?","What do you want to learn? (formal)",7,4],
    ["Ich will Jonglieren lernen.","I want to learn to juggle.",7,4],
    ["Ich will gut Deutsch lernen.","I want to learn German well.",7,4],
    // Vorschlag
    ["Wollen wir Fahrrad fahren?","Shall we go cycling?",7,4],
    ["Wollen wir schwimmen gehen?","Shall we go swimming?",7,4],
    // Fähigkeit
    ["Ich kann sehr gut Ski fahren.","I can ski very well.",7,4],
    ["Kannst du Ski fahren?","Can you ski? (informal)",7,4],
    ["Können Sie Ski fahren?","Can you ski? (formal)",7,4],
    ["Ja, ich kann sehr gut Ski fahren.","Yes, I can ski very well.",7,4],
    ["Ja, ich kann ein bisschen Ski fahren.","Yes, I can ski a bit.",7,4],
    ["Nein, ich kann nicht so gut Ski fahren.","No, I can't ski so well.",7,4],
    ["Nein, ich kann gar nicht Ski fahren.","No, I can't ski at all.",7,4],
    ["Nein, nicht so gut.","No, not so well.",7,4],
    // Sich entschuldigen
    ["Ich bin krank.","I am sick.",7,4],
    ["Oh, das tut mir leid.","Oh, I'm sorry to hear that.",7,4],
    ["Mein Kind ist krank.","My child is sick.",7,4],
    ["Mein Sohn ist krank.","My son is sick.",7,4],
    ["Meine Tochter ist krank.","My daughter is sick.",7,4],
    ["Ich kann heute nicht zum Deutschkurs kommen.","I can't come to German class today.",7,4],
    ["Ich kann heute leider nicht zum Unterricht kommen.","Unfortunately I can't come to class today.",7,4],
    ["Ich sage es der Lehrerin.","I'll tell the teacher (f.).",7,4],
    ["Ich sage es dem Lehrer.","I'll tell the teacher (m.).",7,4],
    ["Ich gehe zum Arzt.","I'm going to the doctor.",7,4],
    ["Gute Besserung!","Get well soon!",7,4],
    // Über die Vergangenheit sprechen
    ["Das habe ich gestern gemacht.","I did this yesterday.",7,4],
    ["Gestern habe ich gearbeitet.","Yesterday I worked.",7,4],
    ["Am Wochenende bin ich Fahrrad gefahren.","On the weekend I went cycling.",7,4],
    ["Lara hat Tee gemacht.","Lara made tea.",7,4],
    ["Ich bin spazieren gegangen.","I went for a walk.",7,4],
    ["Bist du pünktlich gekommen?","Did you arrive on time?",7,4],
    // Strategien
    ["Ja, super!","Yes, great!",7,4],
    ["Nein, nicht so gern.","No, not really.",7,4],
    ["Schade!","What a pity!",7,4],
    ["gestern","yesterday",7,5],
    ["früher","earlier, before",7,5],
    ["die Lehrerin","teacher (f.)",7,0],
    ["der Lehrer","teacher (m.)",7,0],
    ["der Deutschkurs","German class",7,0],
    ["jonglieren","to juggle",7,1],
    // Additional job titles
    ["der Trainer","coach (m.)",7,0],
    ["die Trainerin","coach (f.)",7,0],
    ["der Projektmanager","project manager (m.)",7,0],
    ["die Projektmanagerin","project manager (f.)",7,0],
    ["der Koch","cook (m.)",7,0],
    ["die Köchin","cook (f.)",7,0],
    // Childcare vocabulary
    ["die Gruppe","group",7,0],
    ["der Betreuungsplatz","childcare place",7,0],
    ["die Tagesgruppe","full-day group",7,0],
    ["das Mittagessen","lunch",7,0],
    ["Haben Sie noch Fragen?","Do you have any more questions?",7,4],
    // Additional work-context vocabulary
    ["der Kollege","colleague (m.)",7,0],
    ["der Chef","boss",7,0],
    ["der Lohn","wages, salary",7,0],
    ["die Krankmeldung","sick note",7,0],
    // School vocabulary
    ["die Hausaufgaben","homework (pl.)",7,0],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["vorlesen","to read aloud",7,1],
    ["das Heft","exercise book",7,0],
    ["der Stift","pen",7,0],
    ["der Bleistift","pencil",7,0],
    ["der Kugelschreiber","ballpoint pen",7,0],
    ["der Radiergummi","eraser",7,0],
    ["die Schere","scissors",7,0],
    ["die Grammatik","grammar",7,0],
    ["die Aufgabe","task, exercise",7,0],

    // ===== Cat 8: Lektion 8 — Beruf und Arbeit =====
    ["die Geschichte","story",8,0],
    ["das Krankenhaus","hospital",8,0],
    ["das Interview","interview",8,0],
    ["das Fernsehen","television",8,0],
    ["die Ausbildung","vocational training",8,0],
    ["der Patient","patient",8,0],
    ["der Hausmeister","building manager",8,0],
    ["der Journalist","journalist",8,0],
    ["das Thema","topic",8,0],
    ["eigen-","own, one's own",8,2],
    ["der Mechatroniker","mechatronics technician",8,0],
    ["der Hausmann","househusband, homemaker",8,0],
    ["der Polizist","police officer",8,0],
    ["der Krankenpfleger","male nurse",8,0],
    ["beruflich","professional, work-related",8,2],
    ["der Schüler","pupil, school student",8,0],
    ["der Student","university student",8,0],
    ["studieren","to study at university",8,1],
    ["der Job","job",8,0],
    ["die Stelle","job position",8,0],
    ["selbstständig","self-employed",8,2],
    ["berufstätig","employed, working",8,2],
    ["arbeitslos","unemployed",8,2],
    ["zurzeit","currently",8,5],
    ["der Taxifahrer","taxi driver",8,0],
    ["dauern","to last, take time",8,1],
    ["die Bewerbung","job application",8,0],
    ["das Praktikum","internship",8,0],
    ["die Abteilung","department",8,0],
    ["der Leiter","head, manager",8,0],
    ["geehrt","honoured",8,2],
    ["die Wirtschaft","economics, business",8,0],
    ["das Diplom","diploma",8,0],
    ["gerade","just, right now",8,5],
    ["das Büro","office",8,0],
    ["die Information","information",8,0],
    ["der Gruß","greeting",8,0],
    ["heiraten","to get married",8,1],
    ["eigentlich","actually, really",8,5],
    ["später","later",8,5],
    ["der Reiseführer","tour guide",8,0],
    ["der Tourist","tourist",8,0],
    ["die Berufserfahrung","work experience",8,0],
    ["das Café","café",8,0],
    ["der Stress","stress",8,0],
    ["der Kellner","waiter",8,0],
    ["das Restaurant","restaurant",8,0],
    ["der Architekt","architect",8,0],
    ["der Arbeiter","worker",8,0],
    ["wenig","little, few",8,2],
    ["das Ausland","abroad, foreign country",8,0],
    ["ander-","other, another",8,3],
    ["der Arbeitsplatz","workplace",8,0],
    ["der Traum","dream",8,0],
    ["tagsüber","during the day",8,5],
    ["dreimal","three times",8,5],
    ["bekommen","to receive, get",8,1],
    ["der Sekretär","secretary",8,0],
    ["die Universität","university",8,0],
    ["befristet","temporary, fixed-term",8,2],
    ["die Vollzeit","full-time",8,0],
    ["die Teilzeit","part-time",8,0],
    ["ganztags","full-day",8,5],
    ["halbtags","half-day",8,5],
    ["vormittags","in the mornings",8,5],
    ["nachmittags","in the afternoons",8,5],
    ["die Nachhilfe","tutoring, private lessons",8,0],
    ["montags","on Mondays",8,5],
    ["donnerstags","on Thursdays",8,5],
    ["die Aushilfe","temporary worker",8,0],
    ["dringend","urgent, urgently",8,2],
    ["der Service","service",8,0],
    ["dienstags","on Tuesdays",8,5],
    ["mittwochs","on Wednesdays",8,5],
    ["freitags","on Fridays",8,5],
    ["zahlen","to pay",8,1],
    ["pro","per",8,3],
    ["die Stunde","hour",8,0],
    ["die Nachfrage","inquiry",8,0],
    ["frei","free, available",8,2],
    ["jeweils","each time",8,5],
    ["samstags","on Saturdays",8,5],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["zustimmen","to agree",8,1],
    ["die Kollegin","colleague (f.)",8,0],

    // ===== Cat 9: Lektion 9 — Ämter und Behörden =====
    ["der Führerschein","driving licence",9,0],
    ["das Ticket","ticket",9,0],
    ["das Amt","government office",9,0],
    ["gültig","valid",9,2],
    ["ausländisch","foreign",9,2],
    ["europäisch","European",9,2],
    ["die Europäische Union","European Union",9,0],
    ["jung","young",9,2],
    ["die Fahrt","journey, trip",9,0],
    ["die Fahrkarte","transport ticket",9,0],
    ["der Antrag","application form",9,0],
    ["müssen","must, have to",9,1],
    ["der Ausweis","ID card",9,0],
    ["mitbringen","to bring along",9,1],
    ["die Papiere","papers, documents",9,0],
    ["unterschreiben","to sign",9,1],
    ["bar","cash",9,3],
    ["der Automat","machine, vending machine",9,0],
    ["funktionieren","to work, function",9,1],
    ["das Ziel","goal, destination",9,0],
    ["wählen","to choose, select",9,1],
    ["der Erwachsene","adult",9,0],
    ["auswählen","to select",9,1],
    ["man","one, people (impersonal)",9,3],
    ["zuerst","first of all",9,5],
    ["der Schluss","end, conclusion",9,0],
    ["leise","quiet, soft",9,2],
    ["zuhören","to listen",9,1],
    ["warten","to wait",9,1],
    ["die Gebühr","fee, charge",9,0],
    ["die Kasse","cash desk, checkout",9,0],
    ["lachen","to laugh",9,1],
    ["der Moment","moment",9,0],
    ["beantragen","to apply for",9,1],
    ["dürfen","to be allowed to",9,1],
    ["die Achtung","attention, caution",9,0],
    ["die Zigarette","cigarette",9,0],
    ["rauchen","to smoke",9,1],
    ["langsam","slow",9,2],
    ["der Parkplatz","parking space",9,0],
    ["parken","to park",9,1],
    ["erlaubt","permitted",9,2],
    ["verboten","forbidden",9,2],
    ["das Gepäck","luggage",9,0],
    ["abgeben","to hand in, submit",9,1],
    ["mitnehmen","to take along",9,1],
    ["allein","alone",9,2],
    ["die Behörde","authority, government office",9,0],
    ["die Person","person",9,0],
    ["der Geburtsname","maiden name, birth name",9,0],
    ["das Geschlecht","gender",9,0],
    ["der Ausländer","foreigner",9,0],
    ["getrennt","separated",9,2],
    ["männlich","male",9,2],
    ["weiblich","female",9,2],
    ["der Angehörige","relative, family member",9,0],
    ["bedeuten","to mean",9,1],
    ["verstehen","to understand",9,1],
    ["die Sprachenschule","language school",9,0],
    ["besuchen","to attend, visit",9,1],
    ["die Auskunft","information, inquiry",9,0],
    ["die Erlaubnis","permission",9,0],
    ["die Erklärung","explanation, declaration",9,0],
    ["das Dokument","document",9,0],
    ["das Geld","money",9,0],
    ["genug","enough",9,5],
    ["das Einkommen","income",9,0],
    ["die Reise","journey, travel",9,0],
    ["die Versicherung","insurance",9,0],
    ["die Botschaft","embassy",9,0],
    ["das Visum","visa",9,0],
    ["holen","to fetch, get",9,1],
    ["der Mitarbeiter","employee, staff member",9,0],
    ["der Beamte","official, civil servant",9,0],
    ["verdienen","to earn",9,1],
    ["der Pass","passport",9,0],
    ["reisen","to travel",9,1],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["die Postkarte","postcard",9,0],

    // ===== Cat 10: Lektion 10 — Gesundheit und Krankheit =====
    ["der Klub","club",10,0],
    ["die Notaufnahme","emergency room",10,0],
    ["der Bereich","area, zone",10,0],
    ["die Tablette","tablet, pill",10,0],
    ["das Auge","eye",10,0],
    ["wehtun","to hurt, ache",10,1],
    ["der Unfall","accident",10,0],
    ["der Doktor","doctor (informal)",10,0],
    ["der Schmerz","pain",10,0],
    ["sollen","should, supposed to",10,1],
    ["beide","both",10,3],
    ["lustig","funny, fun",10,2],
    ["schlimm","bad, serious",10,2],
    ["die Idee","idea",10,0],
    ["das Bein","leg",10,0],
    ["das Haar","hair",10,0],
    ["das Ohr","ear",10,0],
    ["der Arm","arm",10,0],
    ["der Bauch","belly, stomach",10,0],
    ["der Finger","finger",10,0],
    ["der Fuß","foot",10,0],
    ["der Hals","throat, neck",10,0],
    ["der Kopf","head",10,0],
    ["der Rücken","back",10,0],
    ["die Brust","chest",10,0],
    ["die Hand","hand",10,0],
    ["die Nase","nose",10,0],
    ["der Mund","mouth",10,0],
    ["der Zahn","tooth",10,0],
    ["ausfallen","to be cancelled",10,1],
    ["die Nachricht","message, news",10,0],
    ["der Kuss","kiss",10,0],
    ["gesund","healthy",10,2],
    ["hoffentlich","hopefully",10,5],
    ["der Bekannte","acquaintance",10,0],
    ["der Schritt","step",10,0],
    ["ein paar","a few",10,3],
    ["die Medizin","medicine, medication",10,0],
    ["die Apotheke","pharmacy",10,0],
    ["das Fieber","fever",10,0],
    ["der Husten","cough",10,0],
    ["die Salbe","ointment, cream",10,0],
    ["verwenden","to use",10,1],
    ["die Gesundheit","health",10,0],
    ["der Schnupfen","cold, runny nose",10,0],
    ["tun","to do",10,1],
    ["der Absender","sender",10,0],
    ["der Ort","place, location",10,0],
    ["der Empfänger","recipient",10,0],
    ["die Anrede","salutation",10,0],
    ["das Datum","date",10,0],
    ["die Unterschrift","signature",10,0],
    ["die Sprechstunde","consultation hours",10,0],
    ["der Notfall","emergency",10,0],
    ["in der Nähe","nearby",10,4],
    ["die Minute","minute",10,0],
    ["in Ordnung","all right, OK",10,4],
    ["vorbeikommen","to come by, drop in",10,1],
    ["die Versichertenkarte","health insurance card",10,0],
    ["der Boden","floor, ground",10,0],
    ["liegen","to lie down",10,1],
    ["der Notarzt","emergency doctor",10,0],
    ["stark","strong, severe",10,2],
    ["die Hilfe","help",10,0],
    ["plötzlich","suddenly",10,5],
    ["passieren","to happen",10,1],
    ["das Medikament","medication",10,0],
    ["das Motorrad","motorcycle",10,0],
    ["die Verletzung","injury",10,0],
    ["Hoffentlich!","Hopefully!",10,4],
    ["Bis später.","See you later.",10,4],
    ["Oh, nein.","Oh no.",10,4],
    ["Oje!","Oh dear!",10,4],
    ["Ach so.","I see.",10,4],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["fehlen","to be missing, to miss",10,1],
    ["die Kopfschmerzen","headache (pl.)",10,0],

    // ===== Cat 11: Lektion 11 — In der Stadt unterwegs =====
    ["die Werkstatt","workshop, garage",11,0],
    ["der Schlüssel","key",11,0],
    ["die Autobahn","motorway",11,0],
    ["die Brücke","bridge",11,0],
    ["die Metzgerei","butcher's shop",11,0],
    ["die Post","post office",11,0],
    ["das Hotel","hotel",11,0],
    ["das Museum","museum",11,0],
    ["die Ampel","traffic light",11,0],
    ["die Tankstelle","petrol station",11,0],
    ["der Stadtplan","city map",11,0],
    ["fremd","foreign, unfamiliar",11,2],
    ["fliegen","to fly",11,1],
    ["das Flugzeug","aeroplane",11,0],
    ["die Straßenbahn","tram",11,0],
    ["die U-Bahn","underground, subway",11,0],
    ["der Bus","bus",11,0],
    ["die S-Bahn","suburban train",11,0],
    ["wohin","where to",11,3],
    ["die Station","stop, station",11,0],
    ["der Lkw","lorry, truck",11,0],
    ["die Haltestelle","bus/tram stop",11,0],
    ["die Buchhandlung","bookshop",11,0],
    ["sitzen","to sit",11,1],
    ["die Bücherei","library",11,0],
    ["der Baum","tree",11,0],
    ["die Bank","bank",11,0],
    ["an","at, by (preposition)",11,3],
    ["auf","on (preposition)",11,3],
    ["hinter","behind",11,3],
    ["neben","next to, beside",11,3],
    ["über","above, over",11,3],
    ["unter","below, under",11,3],
    ["zwischen","between",11,3],
    ["die Fußgängerzone","pedestrian zone",11,0],
    ["das Konzert","concert",11,0],
    ["ausleihen","to borrow, lend",11,1],
    ["kopieren","to copy, photocopy",11,1],
    ["die Ecke","corner",11,0],
    ["abfahren","to depart",11,1],
    ["das Gleis","platform, track",11,0],
    ["einsteigen","to board, get on",11,1],
    ["die Verspätung","delay",11,0],
    ["umsteigen","to change trains",11,1],
    ["aussteigen","to get off",11,1],
    ["die Abfahrt","departure",11,0],
    ["die Ankunft","arrival",11,0],
    ["der Anschluss","connection",11,0],
    ["der Bahnsteig","platform",11,0],
    ["direkt","direct",11,2],
    ["die Durchsage","announcement",11,0],
    ["der Schalter","ticket counter",11,0],
    ["hin und zurück","return, round trip",11,4],
    ["der Fahrplan","timetable",11,0],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["buchen","to book",11,1],
    ["folgen","to follow",11,1],
    ["der See","lake",11,0],
    ["der Tunnel","tunnel",11,0],
    ["durch","through (+ accusative)",11,5],

    // ===== Cat 12: Lektion 12 — Kundenservice =====
    ["die Tüte","bag (plastic/paper)",12,0],
    ["die Rechnung","bill, invoice",12,0],
    ["kaputt","broken",12,2],
    ["reparieren","to repair",12,1],
    ["sauer","annoyed, angry",12,2],
    ["unfreundlich","unfriendly",12,2],
    ["normal","normal",12,2],
    ["das Heimatland","home country",12,0],
    ["das Training","training session",12,0],
    ["die Kleider","clothes",12,0],
    ["nähen","to sew",12,1],
    ["die Reparatur","repair",12,0],
    ["die Aussage","statement",12,0],
    ["der Techniker","technician",12,0],
    ["die Heizung","heating",12,0],
    ["der Drucker","printer",12,0],
    ["das Modell","model",12,0],
    ["die Garantie","guarantee, warranty",12,0],
    ["vorbeibringen","to bring in",12,1],
    ["die Tür","door",12,0],
    ["das Fenster","window",12,0],
    ["das Papier","paper",12,0],
    ["das Licht","light",12,0],
    ["empfehlen","to recommend",12,1],
    ["reservieren","to reserve, book",12,1],
    ["die Rezeption","reception",12,0],
    ["die Ansage","announcement, recorded message",12,0],
    ["drücken","to press",12,1],
    ["hinterlassen","to leave a message",12,1],
    ["zurückrufen","to call back",12,1],
    ["draußen","outside",12,5],
    ["weg","gone, away",12,5],
    ["die Kaffeemaschine","coffee machine",12,0],
    ["der Friseur","hairdresser",12,0],
    ["bestellen","to order",12,1],
    ["das Angebot","offer, deal",12,0],
    ["anbieten","to offer",12,1],
    ["der Jugendliche","young person, teenager",12,0],
    ["die Gebrauchsanweisung","instruction manual",12,0],
    ["die Reinigung","cleaning",12,0],
    ["der Stecker","plug",12,0],
    ["die Steckdose","socket, outlet",12,0],
    ["ziehen","to pull",12,1],
    ["oben","above, upstairs",12,5],
    ["der Essig","vinegar",12,0],
    ["die Taste","button, key",12,0],
    ["die Sekunde","second (time)",12,0],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["senden","to send (formal)",12,1],

    // ===== Cat 13: Lektion 13 — Neue Kleider =====
    ["die Jacke","jacket",13,0],
    ["der Mantel","coat",13,0],
    ["dünn","thin",13,2],
    ["weit","wide, loose",13,2],
    ["die Kleidung","clothing",13,0],
    ["die Bluse","blouse",13,0],
    ["das T-Shirt","T-shirt",13,0],
    ["der Schuh","shoe",13,0],
    ["die Hose","trousers",13,0],
    ["der Rock","skirt",13,0],
    ["das Kleid","dress",13,0],
    ["der Stiefel","boot",13,0],
    ["der Pullover","jumper, pullover",13,0],
    ["die Socke","sock",13,0],
    ["der Strumpf","stocking",13,0],
    ["die Jeans","jeans",13,0],
    ["das Tuch","scarf, cloth",13,0],
    ["das Hemd","shirt",13,0],
    ["der Anzug","suit",13,0],
    ["die Brille","glasses",13,0],
    ["langweilig","boring",13,2],
    ["der Schirm","umbrella",13,0],
    ["perfekt","perfect",13,2],
    ["stehen","to suit (clothing)",13,1],
    ["die Bratwurst","bratwurst, grilled sausage",13,0],
    ["die Landschaft","landscape, scenery",13,0],
    ["der Berg","mountain",13,0],
    ["das Dorf","village",13,0],
    ["der Wald","forest",13,0],
    ["die Nordsee","North Sea",13,0],
    ["der Strand","beach",13,0],
    ["das Meer","sea",13,0],
    ["der Hafen","harbour, port",13,0],
    ["nie","never",13,5],
    ["besser","better",13,2],
    ["am besten","best",13,4],
    ["rückwärts","backwards",13,5],
    ["vorwärts","forwards",13,5],
    ["dabei","at the same time",13,5],
    ["schwer","heavy, difficult",13,2],
    ["der Musiker","musician",13,0],
    ["trainieren","to train, practise",13,1],
    ["Rad fahren","to cycle",13,1],
    ["der Rekord","record",13,0],
    ["am liebsten","most preferably",13,4],
    ["am meisten","most",13,4],
    ["zufrieden","satisfied, content",13,2],
    ["der Witz","joke",13,0],
    ["dies-","this (demonstrative)",13,3],
    ["welch-","which (question word)",13,3],
    ["der Koffer","suitcase",13,0],
    ["gehören","to belong to",13,1],
    ["der Wochentag","day of the week",13,0],
    ["das Erdgeschoss","ground floor",13,0],
    ["das Obergeschoss","upper floor",13,0],
    ["das Untergeschoss","basement",13,0],
    ["der Ausgang","exit",13,0],
    ["die Drogerie","drugstore, chemist",13,0],
    ["die Kosmetik","cosmetics",13,0],
    ["der Schmuck","jewellery",13,0],
    ["das Geschirr","crockery, dishes",13,0],
    ["das Glas","glass",13,0],
    ["die Mode","fashion",13,0],
    ["der Eingang","entrance",13,0],
    ["wissen","to know",13,1],
    ["die Seife","soap",13,0],
    ["die Zahnbürste","toothbrush",13,0],
    ["die Zahnpasta","toothpaste",13,0],
    ["die Größe","size",13,0],
    ["anprobieren","to try on",13,1],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["tauschen","to swap, exchange",13,1],
    ["die Tasche","bag",13,0],
    ["die Armbanduhr","wristwatch",13,0],
    ["die Kette","necklace, chain",13,0],

    // ===== Cat 14: Lektion 14 — Feste =====
    ["der Geburtstag","birthday",14,0],
    ["der Reifen","hoop, tyre",14,0],
    ["der Abschied","farewell",14,0],
    ["bald","soon",14,5],
    ["beginnen","to begin, start",14,1],
    ["die Arbeitsstelle","workplace, job",14,0],
    ["das Glück","luck, happiness",14,0],
    ["die Freude","joy",14,0],
    ["wünschen","to wish",14,1],
    ["gratulieren","to congratulate",14,1],
    ["der Glückwunsch","congratulations",14,0],
    ["glauben","to believe, think",14,1],
    ["erste","first (ordinal)",14,3],
    ["zweite","second (ordinal)",14,3],
    ["dritte","third (ordinal)",14,3],
    ["die Blume","flower",14,0],
    ["der Karneval","carnival",14,0],
    ["letzt-","last",14,3],
    ["mitmachen","to join in",14,1],
    ["der Feiertag","public holiday",14,0],
    ["lieben","to love",14,1],
    ["wunderbar","wonderful",14,2],
    ["der Nachtisch","dessert",14,0],
    ["der Laptop","laptop",14,0],
    ["schmutzig","dirty",14,2],
    ["waschen","to wash",14,1],
    ["der Großvater","grandfather",14,0],
    ["die Feier","celebration, party",14,0],
    ["organisieren","to organise",14,1],
    ["Bescheid geben","to let know, inform",14,4],
    ["der Flug","flight",14,0],
    ["werden","to become, will",14,1],
    ["einladen","to invite",14,1],
    ["sich freuen","to look forward to",14,1],
    ["das Fest","festival, celebration",14,0],
    ["herzlich","heartfelt, warm",14,2],
    ["der Gast","guest",14,0],
    ["der Grund","reason",14,0],
    ["bitten","to ask, request",14,1],
    ["das Weihnachten","Christmas",14,0],
    ["das Ostern","Easter",14,0],
    ["das Silvester","New Year's Eve",14,0],
    ["das Neujahr","New Year",14,0],
    ["gewinnen","to win",14,1],
    ["der Verwandte","relative",14,0],
    ["die Karte","card",14,0],
    ["die Hochzeit","wedding",14,0],
    ["Herzlichen Glückwunsch!","Congratulations!",14,4],
    ["Frohe Ostern!","Happy Easter!",14,4],
    ["Frohe Weihnachten!","Merry Christmas!",14,4],
    ["Ein gutes neues Jahr!","Happy New Year!",14,4],
    ["Viele Grüße","Best regards",14,4],
    ["Herzliche Grüße","Kind regards",14,4],
    ["Mit freundlichen Grüßen","Yours sincerely",14,4],
    ["Alles Gute zum Geburtstag!","Happy Birthday!",14,4],
    ["Alles Liebe zum Geburtstag!","Happy Birthday! (with love)",14,4],
    // Additional — Kasus, Präpositionen & Personalpronomen
    ["schenken","to give as a gift",14,1],
    ["der Blumenstrauß","bouquet of flowers",14,0],
  ],
  // Batches are auto-generated below (groups of 8 within each Lektion)
  batches: [] as number[][],
};

// Build batches: 8 Lektion words per batch, partitioned by Lektion (no cross-Lektion
// batches). The 33 Anweisungen im Kurs (cat 0) are distributed one per batch across
// the first 33 Lektion batches so they're absorbed gradually instead of hit as a
// demotivating wall up front.
(function buildBatches() {
  var anweisungen: number[] = [];
  var byCat: {[k: number]: number[]} = {};
  VOCAB_A11_DATA.words.forEach(function(w, i) {
    var ci = w[2] as number;
    if (ci === 0) { anweisungen.push(i); return; }
    if (!byCat[ci]) byCat[ci] = [];
    byCat[ci].push(i);
  });
  var batches: number[][] = [];
  Object.keys(byCat).sort(function(a, b) { return Number(a) - Number(b); }).forEach(function(ci) {
    var indices = byCat[Number(ci)];
    for (var i = 0; i < indices.length; i += 8) {
      batches.push(indices.slice(i, i + 8));
    }
  });
  // Append one Anweisung to each of the first N batches
  anweisungen.forEach(function(wi, k) {
    if (batches[k]) batches[k].push(wi);
  });
  VOCAB_A11_DATA.batches = batches;
})();
